// All Hypixel Build Battle Guess the Build themes with accepted aliases
// Aliases are alternate names/shortcuts that count as correct answers

export interface GuessBuildTheme {
  theme: string;
  aliases?: string[];
}

export const GUESS_BUILD_THEMES: GuessBuildTheme[] = [
  // ── Easy ──
  { theme: 'Pig' },
  { theme: 'Tree' },
  { theme: 'House' },
  { theme: 'Dog' },
  { theme: 'Cat' },
  { theme: 'Sun' },
  { theme: 'Rainbow' },
  { theme: 'Chair' },
  { theme: 'Cake' },
  { theme: 'Apple' },
  { theme: 'Boat' },
  { theme: 'Frog' },
  { theme: 'Snowman' },
  { theme: 'Island' },
  { theme: 'Mushroom' },
  { theme: 'Ball' },
  { theme: 'Flower' },
  { theme: 'Fish' },
  { theme: 'Bird' },
  { theme: 'Candy' },
  { theme: 'Horse' },
  { theme: 'Sword' },
  { theme: 'Shield' },
  { theme: 'Dragon' },
  { theme: 'Robot' },
  { theme: 'Castle' },
  { theme: 'Tower' },
  { theme: 'Bridge' },
  { theme: 'Mountain' },
  { theme: 'Volcano' },
  { theme: 'Farm' },
  { theme: 'Barn' },
  { theme: 'Lighthouse' },
  { theme: 'Windmill' },
  { theme: 'Guitar' },
  { theme: 'Piano' },
  { theme: 'Diamond' },
  { theme: 'Creeper' },
  { theme: 'Enderman' },
  { theme: 'Spider' },
  { theme: 'Cow' },
  { theme: 'Chicken' },
  { theme: 'Duck' },
  { theme: 'Bee' },
  { theme: 'Butterfly' },
  { theme: 'Snail' },
  { theme: 'Crab' },
  { theme: 'Shark' },
  { theme: 'Whale' },
  { theme: 'Turtle' },
  { theme: 'Fox' },
  { theme: 'Wolf' },
  { theme: 'Bear' },
  { theme: 'Rabbit' },
  { theme: 'Elephant' },
  { theme: 'Giraffe' },
  { theme: 'Lion' },
  { theme: 'Penguin' },
  { theme: 'Flamingo' },
  { theme: 'Eagle' },
  { theme: 'Bat' },
  { theme: 'Snake' },
  { theme: 'Crocodile', aliases: ['croc', 'alligator', 'gator'] },
  { theme: 'Cactus' },
  { theme: 'Cloud' },
  { theme: 'Moon' },
  { theme: 'Star' },
  { theme: 'Rocket', aliases: ['rocket ship'] },
  { theme: 'Alien' },
  { theme: 'Astronaut' },
  { theme: 'Tank' },
  { theme: 'Car' },
  { theme: 'Bus' },
  { theme: 'Train' },
  { theme: 'Bicycle', aliases: ['bike'] },
  { theme: 'Airplane', aliases: ['plane', 'aeroplane'] },
  { theme: 'Helicopter' },
  { theme: 'Submarine' },
  { theme: 'Pickaxe' },
  { theme: 'Axe' },
  { theme: 'Bow' },
  { theme: 'Arrow' },
  { theme: 'Hammer' },
  { theme: 'Cannon' },
  { theme: 'Campfire' },
  { theme: 'Tent' },
  { theme: 'Igloo' },
  { theme: 'Snowflake' },
  { theme: 'Ice Cream', aliases: ['icecream', 'ice-cream'] },
  { theme: 'Pizza' },
  { theme: 'Hamburger', aliases: ['burger', 'cheeseburger'] },
  { theme: 'Hot Dog', aliases: ['hotdog'] },
  { theme: 'Cupcake' },
  { theme: 'Cookie' },
  { theme: 'Donut', aliases: ['doughnut'] },
  { theme: 'Taco' },
  { theme: 'Sushi' },
  { theme: 'Popcorn' },
  { theme: 'Watermelon' },
  { theme: 'Pineapple' },
  { theme: 'Banana' },
  { theme: 'Strawberry' },
  { theme: 'Grapes' },
  { theme: 'Cherry' },
  { theme: 'Pumpkin' },
  { theme: 'Carrot' },
  { theme: 'Broccoli' },
  { theme: 'Corn' },
  { theme: 'Sunflower' },
  { theme: 'Rose' },
  { theme: 'Tulip' },
  { theme: 'Daisy' },
  { theme: 'Lantern' },
  { theme: 'Lamp' },
  { theme: 'Table' },
  { theme: 'Bed' },
  { theme: 'Sofa', aliases: ['couch'] },
  { theme: 'Bookshelf' },
  { theme: 'Clock' },
  { theme: 'Cup' },
  { theme: 'Mug' },
  { theme: 'Bottle' },
  { theme: 'Vase' },
  { theme: 'Key' },
  { theme: 'Lock' },
  { theme: 'Map' },
  { theme: 'Book' },
  { theme: 'Pencil' },
  { theme: 'Scissors' },
  { theme: 'Umbrella' },
  { theme: 'Glasses', aliases: ['spectacles', 'sunglasses'] },
  { theme: 'Hat' },
  { theme: 'Crown' },
  { theme: 'Ring' },
  { theme: 'Shoe' },
  { theme: 'Boot' },
  { theme: 'Glove' },
  { theme: 'Backpack', aliases: ['rucksack'] },
  { theme: 'Trophy' },
  { theme: 'Medal' },
  { theme: 'Coin' },
  { theme: 'Diamond Ring' },
  { theme: 'Magnet' },
  { theme: 'Compass' },
  { theme: 'Hourglass' },
  { theme: 'Telescope' },
  { theme: 'Microscope' },
  { theme: 'Binoculars' },
  { theme: 'Lantern' },
  { theme: 'Torch' },
  { theme: 'Firework' },
  { theme: 'Balloon' },
  { theme: 'Kite' },
  { theme: 'Parachute' },
  { theme: 'Anchor' },
  { theme: 'Wheel' },
  { theme: 'Propeller' },

  // ── Medium ──
  { theme: 'Knight' },
  { theme: 'Wizard' },
  { theme: 'Pirate' },
  { theme: 'Ninja' },
  { theme: 'Samurai' },
  { theme: 'Viking' },
  { theme: 'Gladiator' },
  { theme: 'Pharaoh' },
  { theme: 'Mermaid' },
  { theme: 'Unicorn' },
  { theme: 'Phoenix' },
  { theme: 'Medusa' },
  { theme: 'Cyclops' },
  { theme: 'Werewolf' },
  { theme: 'Vampire' },
  { theme: 'Zombie' },
  { theme: 'Skeleton' },
  { theme: 'Ghost' },
  { theme: 'Witch' },
  { theme: 'Warlock' },
  { theme: 'Griffin' },
  { theme: 'Pegasus' },
  { theme: 'Centaur' },
  { theme: 'Minotaur' },
  { theme: 'Hydra' },
  { theme: 'Kraken' },
  { theme: 'Golem' },
  { theme: 'Hospital' },
  { theme: 'School' },
  { theme: 'Church', aliases: ['cathedral'] },
  { theme: 'Prison', aliases: ['jail'] },
  { theme: 'Museum' },
  { theme: 'Library' },
  { theme: 'Zoo' },
  { theme: 'Stadium' },
  { theme: 'Skyscraper' },
  { theme: 'Pyramid' },
  { theme: 'Sphinx' },
  { theme: 'Eiffel Tower' },
  { theme: 'Big Ben' },
  { theme: 'Colosseum' },
  { theme: 'Taj Mahal' },
  { theme: 'Great Wall', aliases: ['great wall of china'] },
  { theme: 'Leaning Tower of Pisa', aliases: ['tower of pisa'] },
  { theme: 'Statue of Liberty' },
  { theme: 'Mount Everest', aliases: ['everest'] },
  { theme: 'Stonehenge' },
  { theme: 'Parthenon' },
  { theme: 'Acropolis' },
  { theme: 'Notre Dame', aliases: ['notre-dame'] },
  { theme: 'Buckingham Palace' },
  { theme: 'White House' },
  { theme: 'Space Shuttle', aliases: ['spaceshuttle'] },
  { theme: 'Space Station', aliases: ['iss', 'international space station'] },
  { theme: 'Black Hole' },
  { theme: 'Solar System' },
  { theme: 'Galaxy' },
  { theme: 'Nebula' },
  { theme: 'Supernova' },
  { theme: 'Observatory' },
  { theme: 'Roller Coaster' },
  { theme: 'Ferris Wheel' },
  { theme: 'Carousel' },
  { theme: 'Water Slide' },
  { theme: 'Basketball' },
  { theme: 'Football' },
  { theme: 'Baseball' },
  { theme: 'Soccer Ball', aliases: ['football'] },
  { theme: 'Tennis Racket', aliases: ['tennis racquet'] },
  { theme: 'Golf Club' },
  { theme: 'Bowling Ball' },
  { theme: 'Swimming Pool' },
  { theme: 'Surfboard' },
  { theme: 'Skateboard' },
  { theme: 'Video Game Controller', aliases: ['controller', 'gamepad', 'game controller'] },
  { theme: 'Television', aliases: ['tv', 'TV'] },
  { theme: 'Computer' },
  { theme: 'Keyboard' },
  { theme: 'Smartphone', aliases: ['phone', 'mobile phone', 'cell phone'] },
  { theme: 'Camera' },
  { theme: 'Headphones' },
  { theme: 'Microphone', aliases: ['mic'] },
  { theme: 'Calculator' },
  { theme: 'Printer' },
  { theme: 'Satellite' },
  { theme: 'Lighthouse' },
  { theme: 'Oil Rig' },
  { theme: 'Wind Turbine', aliases: ['windmill'] },
  { theme: 'Solar Panel' },
  { theme: 'Nuclear Power Plant' },
  { theme: 'Dam' },
  { theme: 'Aqueduct' },
  { theme: 'Sewage System' },
  { theme: 'Fire Station' },
  { theme: 'Police Station' },
  { theme: 'Hospital' },
  { theme: 'Shopping Mall', aliases: ['mall'] },
  { theme: 'Supermarket', aliases: ['grocery store'] },
  { theme: 'Restaurant' },
  { theme: 'Hotel' },
  { theme: 'Airport' },
  { theme: 'Train Station' },
  { theme: 'Subway', aliases: ['metro', 'underground'] },
  { theme: 'Cruise Ship' },
  { theme: 'Aircraft Carrier' },
  { theme: 'Battleship' },
  { theme: 'Pirate Ship' },
  { theme: 'Hot Air Balloon' },
  { theme: 'Blimp', aliases: ['zeppelin'] },
  { theme: 'Fighter Jet' },
  { theme: 'UFO', aliases: ['unidentified flying object', 'ufo'] },
  { theme: 'Treehouse' },
  { theme: 'Birdhouse' },
  { theme: 'Doghouse' },

  // ── Hard / Abstract ──
  { theme: 'Justice' },
  { theme: 'Freedom' },
  { theme: 'Democracy' },
  { theme: 'Equality' },
  { theme: 'Peace' },
  { theme: 'War' },
  { theme: 'Love' },
  { theme: 'Hate' },
  { theme: 'Life' },
  { theme: 'Death' },
  { theme: 'Time' },
  { theme: 'Money' },
  { theme: 'Power' },
  { theme: 'Knowledge' },
  { theme: 'Wisdom' },
  { theme: 'Beauty' },
  { theme: 'Truth' },
  { theme: 'Hope' },
  { theme: 'Dream' },
  { theme: 'Nightmare' },
  { theme: 'Memory' },
  { theme: 'Emotion' },
  { theme: 'Gravity' },
  { theme: 'Electricity' },
  { theme: 'Magnetism' },
  { theme: 'Chemistry' },
  { theme: 'Physics' },
  { theme: 'Mathematics', aliases: ['math', 'maths'] },
  { theme: 'Philosophy' },
  { theme: 'Psychology' },
  { theme: 'Archaeology' },
  { theme: 'Evolution' },
  { theme: 'Revolution' },
  { theme: 'Pollution' },
  { theme: 'Climate Change', aliases: ['global warming'] },
  { theme: 'Deforestation' },
  { theme: 'Extinction' },
  { theme: 'Pandemic' },
  { theme: 'Imagination' },
  { theme: 'Creativity' },
  { theme: 'Innovation' },
  { theme: 'Technology' },
  { theme: 'Artificial Intelligence', aliases: ['ai', 'AI', 'artificial intelligence'] },
  { theme: 'Cybersecurity' },
  { theme: 'Cryptocurrency', aliases: ['crypto', 'bitcoin'] },
  { theme: 'Social Media' },
  { theme: 'Internet' },
  { theme: 'Virtual Reality', aliases: ['vr', 'VR'] },
  { theme: 'Augmented Reality', aliases: ['ar', 'AR'] },
];