export interface GuessBuildTheme {
  theme: string;
  aliases?: string[];
}

export const GUESS_BUILD_THEMES: GuessBuildTheme[] = [
  { theme: 'Air Horn', aliases: ['tromba'] },
  { theme: 'Airport' },
  { theme: 'Airship', aliases: ['zeplin', 'luftskib', 'luftskip', 'dirigible', 'dirigivel', 'sterowiec', 'dirigibile', 'dirigeable', 'luftschiff', 'vzducholod', '飛行船', 'léghajó', 'дирижабль'] },
  { theme: 'Alarm Clock', aliases: ['budik'] },
  { theme: 'Ambulance', aliases: ['ambulan'] },
  { theme: 'Anchor', aliases: ['capa'] },
  { theme: 'Angel', aliases: ['ange', 'engel'] },
  { theme: 'Angry' },
  { theme: 'Animal', aliases: ['dyr'] },
  { theme: 'Ant' },
  { theme: 'Antivirus' },
  { theme: 'Anvil', aliases: ['ors'] },
  { theme: 'Apocalypse', aliases: ['kiyamet'] },
  { theme: 'Apple', aliases: ['mar', 'elma', 'pomme'] },
  { theme: 'Apple Pie', aliases: ['eplepai'] },
  { theme: 'Apple Tree', aliases: ['pom'] },
  { theme: 'Aquarium', aliases: ['aquario', 'akvarium', 'aquarium', 'аквариум', 'акваріум'] },
  { theme: 'Arcade', aliases: ['arkad'] },
  { theme: 'Archer', aliases: ['okcu'] },
  { theme: 'Arctic', aliases: ['arkti'] },
  { theme: 'Arm' },
  { theme: 'Armor', aliases: ['zirh'] },
  { theme: 'Army', aliases: ['armata'] },
  { theme: 'Arrow', aliases: ['ok', 'pil', 'sip', 'bolt'] },
  { theme: 'Art', aliases: ['arta'] },
  { theme: 'Astronaut', aliases: ['urhajos', 'űrhajó'] },
  { theme: 'Atmosphere', aliases: ['legkor'] },
  { theme: 'Atom' },
  { theme: 'Australia' },
  { theme: 'Autumn', aliases: ['osz'] },
  { theme: 'Avocado', aliases: ['avocat'] },
  { theme: 'Award', aliases: ['dij', 'palkinto'] },
  { theme: 'Axe', aliases: ['balta'] },
  { theme: 'Axolotl', aliases: ['axolot'] },
  { theme: 'Baby', aliases: ['baba', 'dziecko', 'bambino', 'дитина', 'ребёнок'] },
  { theme: 'Backflip' },
  { theme: 'Backpack', aliases: ['reppu'] },
  { theme: 'Bacon', aliases: ['spek'] },
  { theme: 'Badge' },
  { theme: 'Bag', aliases: ['mala', 'borsa', 'canta', 'sac', 'сумка'] },
  { theme: 'Baguette', aliases: ['baget'] },
  { theme: 'Bakery', aliases: ['firin'] },
  { theme: 'Bald Head', aliases: ['bald'] },
  { theme: 'Balloon', aliases: ['globo'] },
  { theme: 'Bamboo', aliases: ['bambu'] },
  { theme: 'Banana' },
  { theme: 'Band', aliases: ['band', 'banda'] },
  { theme: 'Bandage', aliases: ['side'] },
  { theme: 'Banjo' },
  { theme: 'Bank', aliases: ['bank', 'banca', 'banco'] },
  { theme: 'Banner', aliases: ['flag', '旗', '旗帜', '旗幟'] },
  { theme: 'Bar', aliases: ['bar', '酒場', '술집', 'бар'] },
  { theme: 'Barbeque', aliases: ['bbq'] },
  { theme: 'Barcode', aliases: ['barkod'] },
  { theme: 'Barn', aliases: ['schuur', 'lave', 'barn', '헛간', 'сарай'] },
  { theme: 'Barrel', aliases: ['fas'] },
  { theme: 'Barrier', aliases: ['este', 'barriere'] },
  { theme: 'Baseball', aliases: ['basebol'] },
  { theme: 'Baseball Field', aliases: ['honkbalveld'] },
  { theme: 'Baseball Glove' },
  { theme: 'Basket', aliases: ['cos', 'cesta', '장바구니'] },
  { theme: 'Basketball', aliases: ['baschet'] },
  { theme: 'Basketball Court', aliases: ['basketplan'] },
  { theme: 'Bastion', aliases: ['kale'] },
  { theme: 'Bat', aliases: ['bat'] },
  { theme: 'Bath', aliases: ['bad', 'baie', 'bagno', 'banheira', 'wanna', 'banyo', 'banera', 'baignoire', '浴室', '浴缸', '욕조', 'ванна'] },
  { theme: 'Bathroom', aliases: ['bad', 'baie', 'bagno', 'banyo', '浴室'] },
  { theme: 'Battery', aliases: ['pil'] },
  { theme: 'Battleship', aliases: ['slagskib'] },
  { theme: 'Beach', aliases: ['plaj'] },
  { theme: 'Beach Ball', aliases: ['badboll'] },
  { theme: 'Beach Party' },
  { theme: 'Beanie', aliases: ['lue', 'cepice', 'mutze', 'czapka'] },
  { theme: 'Beans' },
  { theme: 'Bear', aliases: ['ur', 'bar'] },
  { theme: 'Beard', aliases: ['bart', 'ひげ'] },
  { theme: 'Beaver', aliases: ['hod'] },
  { theme: 'Bed Wars' },
  { theme: 'Bedtime' },
  { theme: 'Bee', aliases: ['bi', 'Μέλισσα'] },
  { theme: 'Beef', aliases: ['biff', 'bife', 'biftek', 'bøf'] },
  { theme: 'Beehive', aliases: ['ul', 'alveare', '蜂窩'] },
  { theme: 'Beetle', aliases: ['bille', 'kafer', 'bogar', 'brouk', 'scarafaggio', 'жук'] },
  { theme: 'Bell', aliases: ['bel', 'klokke'] },
  { theme: 'Bell Pepper', aliases: ['papryka'] },
  { theme: 'Belt', aliases: ['pa'] },
  { theme: 'Bench', aliases: ['pad', 'bank', 'banca', 'banco'] },
  { theme: 'Berries', aliases: ['bar', 'baie'] },
  { theme: 'Bicycle', aliases: ['kolo'] },
  { theme: 'Bigfoot', aliases: ['elyeti', 'йети'] },
  { theme: 'Bike Path', aliases: ['radweg'] },
  { theme: 'Bin', aliases: ['poubelle', 'lixo', 'basura', 'mulleimer', 'cop kutusu', 'skraldespand', 'ゴミ箱', '垃圾桶', '쓰레기통', 'мусорноеведро', 'kos', 'cestino', 'roskakori', 'kős', 'søppelkasse'] },
  { theme: 'Bingo' },
  { theme: 'Binoculars', aliases: ['kikare'] },
  { theme: 'Bird', aliases: ['kus'] },
  { theme: 'Bird Bath' },
  { theme: 'Bird Cage' },
  { theme: 'Bird House', aliases: ['fuglehu', 'fuglehus'] },
  { theme: 'Bird Nest', aliases: ['ninho', 'fuglehus'] },
  { theme: 'Birthday', aliases: ['bursdag'] },
  { theme: 'Birthday Party' },
  { theme: 'Biscuit', aliases: ['kek', 'kjek', 'keksi', 'koekje', 'galleta', 'susenka', 'biscuit', 'biscotto', 'biscoito', '餅乾', 'печиво', 'печенье'] },
  { theme: 'Bison', aliases: ['okse'] },
  { theme: 'Black Hole', aliases: ['sorthul'] },
  { theme: 'Blackboard', aliases: ['tavle', 'tafel'] },
  { theme: 'Blacksmith', aliases: ['smid'] },
  { theme: 'Blanket', aliases: ['koc', 'teppe', 'tæppe', 'manta'] },
  { theme: 'Blaze', aliases: ['lohe'] },
  { theme: 'Blender', aliases: ['mixer'] },
  { theme: 'Blimp', aliases: ['zeplin', 'luftskib', 'luftskip', 'dirigible', 'dirigivel', 'sterowiec', 'dirigibile', 'dirigeable', 'luftschiff', 'vzducholod', '飛行船', 'léghajó', 'дирижабль'] },
  { theme: 'Blizzard', aliases: ['nevao', 'tormenta'] },
  { theme: 'Blocks', aliases: ['bloc'] },
  { theme: 'Blueprint', aliases: ['schita'] },
  { theme: 'Board Game', aliases: ['bordspel'] },
  { theme: 'Boat', aliases: ['lod', 'bad', 'bat', 'boot', 'barco', 'bateau', '船', 'лодка', 'човен'] },
  { theme: 'Bomb', aliases: ['bom'] },
  { theme: 'Bone', aliases: ['o', 'kost', 'bone'] },
  { theme: 'Book', aliases: ['bok', 'carte'] },
  { theme: 'Book Shelf', aliases: ['bogreol', 'libreria', 'knihovna', 'bibliotheque'] },
  { theme: 'Bookmark', aliases: ['marcaj', 'marcador'] },
  { theme: 'Bookstore', aliases: ['libreria', 'librărie'] },
  { theme: 'Boomerang', aliases: ['bumeran'] },
  { theme: 'Boots', aliases: ['sko', 'boot', 'boty', 'buty', 'schuhe', '신발'] },
  { theme: 'Border', aliases: ['ram'] },
  { theme: 'Bottle', aliases: ['fle', 'sticla', '瓶'] },
  { theme: 'Bouncy Castle', aliases: ['hoppborg'] },
  { theme: 'Bow and Arrow', aliases: ['yayveok'] },
  { theme: 'Bow Tie', aliases: ['fluga', 'fliege', 'papillon', 'butterfly', '领带'] },
  { theme: 'Bowl', aliases: ['bol', 'skal', 'kase', 'bolle'] },
  { theme: 'Bowling', aliases: ['bolo', '保齡球', '保龄球'] },
  { theme: 'Bowling Ball', aliases: ['bowlingbal', '保齡球', '保龄球'] },
  { theme: 'Bowling Pin', aliases: ['labut'] },
  { theme: 'Box of Chocolate', aliases: ['chokladask'] },
  { theme: 'Boxing Ring', aliases: ['boxring'] },
  { theme: 'Boy' },
  { theme: 'Bracelet', aliases: ['karkoto'] },
  { theme: 'Brain', aliases: ['agy'] },
  { theme: 'Branch' },
  { theme: 'Breakfast', aliases: ['frokost'] },
  { theme: 'Brick' },
  { theme: 'Bridge', aliases: ['pod'] },
  { theme: 'Broccoli', aliases: ['brokul'] },
  { theme: 'Broken', aliases: ['roto'] },
  { theme: 'Broom', aliases: ['kost'] },
  { theme: 'Brush', aliases: ['kefe', 'perie', 'escova', 'pedzel', 'pennello', 'кисть', 'пензель'] },
  { theme: 'Bubbles', aliases: ['bolle'] },
  { theme: 'Buffet', aliases: ['bufe'] },
  { theme: 'Bug', aliases: ['kafer', 'bogar', 'robak', 'bocek', 'brouk', 'insekt', 'inseto', 'insect', 'insetto', 'insecte', 'insecto', 'жук'] },
  { theme: 'Build Battle' },
  { theme: 'Building', aliases: ['yapi', 'construcao', 'costruzione', 'construccion'] },
  { theme: 'Bull', aliases: ['tyr', 'okse'] },
  { theme: 'Bulldozer', aliases: ['raivoso'] },
  { theme: 'Bumblebee', aliases: ['dongo', 'Μέλισσα'] },
  { theme: 'Bumper Cars', aliases: ['dodzsem'] },
  { theme: 'Bunk Bed', aliases: ['ranza'] },
  { theme: 'Bunker', aliases: ['bunkr', 'siginak', 'бункер'] },
  { theme: 'Burger', aliases: ['hamburger', 'hamburguer', 'hamburguesa', 'hampurilainen', '漢堡', 'ハンバーガー'] },
  { theme: 'Bus Stop' },
  { theme: 'Bush', aliases: ['ker', 'arbusto'] },
  { theme: 'Butter', aliases: ['vaj', 'burro'] },
  { theme: 'Butterfly', aliases: ['motyl', 'mariposa', 'papillon', 'butterfly'] },
  { theme: 'Button', aliases: ['gomb'] },
  { theme: 'Cab', aliases: ['taxi', 'taksi', 'taksowka', '택시', '出租车', '計程車', 'タクシー', 'такси', 'таксі'] },
  { theme: 'Cabbage', aliases: ['sla'] },
  { theme: 'Cabinet', aliases: ['skab', 'armario', 'skap', 'dolap', 'schrank', 'шафа', 'шкаф'] },
  { theme: 'Cable', aliases: ['cavo', 'cable', 'kabel', 'kablo', 'cablu'] },
  { theme: 'Cactus' },
  { theme: 'Cage', aliases: ['bur', 'kafe', 'celle', 'клетка'] },
  { theme: 'Cake', aliases: ['torta', 'bolo', 'pasta', 'taart', 'tarta'] },
  { theme: 'Calculator', aliases: ['laskin'] },
  { theme: 'Calendar', aliases: ['agenda'] },
  { theme: 'Camel', aliases: ['teve'] },
  { theme: 'Camera', aliases: ['camera'] },
  { theme: 'Camouflage', aliases: ['alca'] },
  { theme: 'Campfire', aliases: ['fogata'] },
  { theme: 'Campground', aliases: ['kemp'] },
  { theme: 'Can', aliases: ['lata', 'burk', 'cutie', 'puszka', 'lattina', 'plechovka', 'hermetikkbok', 'konzervdoboz', '罐头', 'банка'] },
  { theme: 'Canada' },
  { theme: 'Canal', aliases: ['kanal', 'csatorna'] },
  { theme: 'Candle', aliases: ['mum'] },
  { theme: 'Candy', aliases: ['godi', 'seker'] },
  { theme: 'Candy Cane', aliases: ['acadea'] },
  { theme: 'Cane', aliases: ['bengala', 'cane', 'stock', '杖', '지팡이'] },
  { theme: 'Cannon', aliases: ['tun', 'armata'] },
  { theme: 'Canoe', aliases: ['kano', 'kajak', '划艇'] },
  { theme: 'Cap', aliases: ['cepice', '모자', 'pet', 'kep', 'cap', 'bone', 'sapka', 'mutze', 'czapka'] },
  { theme: 'Cape', aliases: ['capa', 'mantel', 'cape', 'kappe', 'plast', 'umhang', 'kopeny', 'pelerin', 'mantello', '披風', '披风', '망토', 'плащ'] },
  { theme: 'Capybara', aliases: ['kapivar'] },
  { theme: 'Car', aliases: ['carro'] },
  { theme: 'Car Wash' },
  { theme: 'Card Games', aliases: ['kortspel'] },
  { theme: 'Cardboard Box', aliases: ['karton'] },
  { theme: 'Caribbean', aliases: ['caribe'] },
  { theme: 'Carnival' },
  { theme: 'Carpenter', aliases: ['acs'] },
  { theme: 'Carpet', aliases: ['tapi', 'teppe', 'tæppe', 'covor', 'matta', 'dywan', 'tapete', 'tapijt', 'tappeto', 'teppich', 'koberec', 'szonyeg', 'alfombra', '地毯', '양탄자', 'килим', 'ковёр'] },
  { theme: 'Carriage', aliases: ['vogn', 'vagn', 'waggon', 'carroca', 'vervoer', 'carrello', '馬車', '马车', '마차'] },
  { theme: 'Carrot', aliases: ['repa'] },
  { theme: 'Cart' },
  { theme: 'Cartoon' },
  { theme: 'Cash', aliases: ['dinero', 'dinheiro', 'pieniadze'] },
  { theme: 'Cashier', aliases: ['kassa'] },
  { theme: 'Castle', aliases: ['slot', 'kale', 'крепость', 'zamek', 'kastely', 'замок'] },
  { theme: 'Cat', aliases: ['kocka', '고양이'] },
  { theme: 'Catacomb' },
  { theme: 'Catapult' },
  { theme: 'Caterpillar', aliases: ['rup'] },
  { theme: 'Cave', aliases: ['洞穴'] },
  { theme: 'Ceiling Fan', aliases: ['takflakt'] },
  { theme: 'Celebrate', aliases: ['fira', 'свято'] },
  { theme: 'Cell', aliases: ['cel', 'cella', 'celle', 'клетка'] },
  { theme: 'Cement Mixer', aliases: ['betoneira'] },
  { theme: 'Centaur' },
  { theme: 'Cereal', aliases: ['korn'] },
  { theme: 'Cereal Box' },
  { theme: 'Chain', aliases: ['lant', 'ketting', '鎖'] },
  { theme: 'Chainsaw', aliases: ['drujba', 'testere'] },
  { theme: 'Chair', aliases: ['stol', 'stoel'] },
  { theme: 'Chalk', aliases: ['giz', 'krita'] },
  { theme: 'Chandelier', aliases: ['avize'] },
  { theme: 'Checkerboard', aliases: ['damier'] },
  { theme: 'Cheese', aliases: ['kaa', 'kase'] },
  { theme: 'Cheeseburger', aliases: ['cizburger'] },
  { theme: 'Cheesecake', aliases: ['cizkek'] },
  { theme: 'Chef', aliases: ['sef', 'kok', 'szakacs', 'kock', 'koch', 'kokk', 'kokki', 'kuchar', 'bucatar', 'cocinero', '厨师', '廚師'] },
  { theme: 'Chef Hat' },
  { theme: 'Cherry' },
  { theme: 'Chess', aliases: ['sah'] },
  { theme: 'Chestnut', aliases: ['kastan'] },
  { theme: 'Chestplate', aliases: ['peto'] },
  { theme: 'Chicken', aliases: ['pui', 'kure', 'kana', 'tavuk', 'gallina', 'galinha', 'курка', 'курица'] },
  { theme: 'Chicken Nugget', aliases: ['kipnugget'] },
  { theme: 'Chilli', aliases: ['salsa'] },
  { theme: 'Chimney', aliases: ['pipe', 'camino', 'cheminee', 'chimenea'] },
  { theme: 'China', aliases: ['cin', 'cina'] },
  { theme: 'Chip', aliases: ['cip', 'chips', 'chip', '洋芋片'] },
  { theme: 'Chocolate', aliases: ['suklaa'] },
  { theme: 'Chocolate Cake', aliases: ['suklaakakku'] },
  { theme: 'Chocolate Chip Cookie', aliases: ['cookie', 'bolacha'] },
  { theme: 'Chocolate Factory', aliases: ['csokigyar'] },
  { theme: 'Chocolate Milk', aliases: ['csokistej'] },
  { theme: 'Chopsticks', aliases: ['hashi'] },
  { theme: 'Christmas', aliases: ['jul', 'natal', 'joulu', 'karacsony'] },
  { theme: 'Church', aliases: ['kerk', 'templom'] },
  { theme: 'Cinema', aliases: ['cine', 'mozi', 'kino', 'cinema', 'theater', 'biograf', 'bioscoop', 'elokuvateatteri', '电影院', '電影院', 'кінотеатр'] },
  { theme: 'Circle', aliases: ['kor', 'kolo', '원형'] },
  { theme: 'Circus', aliases: ['circ'] },
  { theme: 'Clam', aliases: ['kagylo', 'muschel', 'simpukka'] },
  { theme: 'Clap', aliases: ['tap'] },
  { theme: 'Class' },
  { theme: 'Claw', aliases: ['klo', 'drap', 'karom', '爪子'] },
  { theme: 'Clay', aliases: ['ler', 'ton'] },
  { theme: 'Cliff', aliases: ['klif'] },
  { theme: 'Climbing', aliases: ['maszas', 'escalar', 'escalada', 'escalade', 'wspinaczka', 'arrampicata', 'horolezectvi', 'скелелазіння'] },
  { theme: 'Cloak', aliases: ['cape', 'capa', 'mantel', 'kappe', 'plast', 'umhang', 'kopeny', 'plaszcz', 'pelerin', 'mantello', '披風', '披风', '망토', 'плащ'] },
  { theme: 'Clock', aliases: ['ur', 'klokke', 'ora', 'horloge', 'relogio', 'hourglas', 'orologio', '시계', 'часы', 'годинник'] },
  { theme: 'Closet', aliases: ['skab', 'armario', 'skap', 'szafa', 'dolap', 'toilet', 'armadio', 'schrank', 'garderob', '옷장', 'шафа', 'шкаф'] },
  { theme: 'Clouds', aliases: ['nori'] },
  { theme: 'Clover', aliases: ['apila', 'klaver'] },
  { theme: 'Clown', aliases: ['pelle'] },
  { theme: 'Clown Fish', aliases: ['clownvi'] },
  { theme: 'Coat', aliases: ['ja', 'rock', 'jacke', 'takki', 'casaco', 'abrigo', 'plaszcz'] },
  { theme: 'Coat Hanger', aliases: ['aski'] },
  { theme: 'Cobweb', aliases: ['panza', 'pokhalo', 'telarana', 'pavucina', 'ragnatela', 'spinnenweb', 'spindelvev', 'spindelnat', 'spinnennetz', 'teiadearanha', 'toile d\'araignee', '蜘蛛網', '거미줄', 'クモの巣', 'паутина', 'spindelvæv', 'pajeczyna', 'orumcek agi', '蜘蛛网'] },
  { theme: 'Cockroach', aliases: ['svab', 'scarafaggio'] },
  { theme: 'Coconut', aliases: ['coco'] },
  { theme: 'Cocoon', aliases: ['bab', 'koza'] },
  { theme: 'Coffee', aliases: ['cafe'] },
  { theme: 'Coffee Machine', aliases: ['kavovar'] },
  { theme: 'Coffee Shop', aliases: ['kafe', 'cafe'] },
  { theme: 'Coffin', aliases: ['sarg'] },
  { theme: 'Coin', aliases: ['para', 'piece'] },
  { theme: 'Colored Pencil', aliases: ['kredka', 'buntstift', 'farveblyant'] },
  { theme: 'Colosseum', aliases: ['colisee'] },
  { theme: 'Comb', aliases: ['kam', '梳子', 'расчёска'] },
  { theme: 'Comet', aliases: ['cometa'] },
  { theme: 'Compass', aliases: ['kompa'] },
  { theme: 'Computer', aliases: ['dator'] },
  { theme: 'Concert', aliases: ['konser'] },
  { theme: 'Construction', aliases: ['bau', 'construcao', 'costruzione', 'construccion'] },
  { theme: 'Controller', aliases: ['mando', 'ovladac', 'controller', 'spelkontroll', 'oyunkumandasi'] },
  { theme: 'Conveyor Belt', aliases: ['futoszalag', 'tapisroulant'] },
  { theme: 'Cook', aliases: ['mad', 'kok', 'szakacs', 'sef', 'kock', 'koch', 'kokk', 'kokki', 'kuchar', 'cucina', 'bucatar', 'cocinero', 'cozinhar', '厨师', '廚師'] },
  { theme: 'Cookie', aliases: ['kek', 'kjek', 'keksi', 'koekje', 'cookie', 'galleta', 'susenka', 'biscuit', 'bolacha', 'biscotto', 'biscoito', '餅乾', 'печиво', 'печенье'] },
  { theme: 'Cooking', aliases: ['gatit', 'szakacs', 'cocina', 'cuisine', 'cozinhar'] },
  { theme: 'Coral' },
  { theme: 'Corn', aliases: ['maj', 'korn', 'misir'] },
  { theme: 'Corn Dog', aliases: ['hotdog'] },
  { theme: 'Corner', aliases: ['rog', 'roh', 'colt', 'horn', 'piece'] },
  { theme: 'Cotton Candy', aliases: ['hattara', '棉花糖'] },
  { theme: 'Couch', aliases: ['sofa', 'bank', 'sohva', 'divano', '沙发', '沙發', '소파', 'диван'] },
  { theme: 'Cow', aliases: ['ku', 'kus', 'ko', 'kos'] },
  { theme: 'Cowbell', aliases: ['koebel'] },
  { theme: 'Cowboy', aliases: ['ковбой'] },
  { theme: 'Cowboy Hat' },
  { theme: 'Crab', aliases: ['rak'] },
  { theme: 'Crafting Table', aliases: ['etabli', 'tyopoyta'] },
  { theme: 'Crane', aliases: ['gru', 'crane'] },
  { theme: 'Crate', aliases: ['krat', 'cutie'] },
  { theme: 'Crater' },
  { theme: 'Crayon', aliases: ['krita', 'kredka', 'crayon', 'buntstift', 'farveblyant'] },
  { theme: 'Credit Card', aliases: ['card'] },
  { theme: 'Creeper' },
  { theme: 'Crib' },
  { theme: 'Cricket', aliases: ['syrsa'] },
  { theme: 'Criminal', aliases: ['suclu', 'criminal', 'злочинець'] },
  { theme: 'Crocodile', aliases: ['timsah'] },
  { theme: 'Crossbow', aliases: ['kuse'] },
  { theme: 'Crosswalk', aliases: ['fortau'] },
  { theme: 'Crow' },
  { theme: 'Crowbar', aliases: ['lom'] },
  { theme: 'Crown', aliases: ['tac'] },
  { theme: 'Cruise Ship', aliases: ['cruise'] },
  { theme: 'Cry' },
  { theme: 'Crystal', aliases: ['jewel'] },
  { theme: 'Crystal Ball' },
  { theme: 'Cube', aliases: ['cub', 'kocka', 'kostka', 'wurfel', 'terning'] },
  { theme: 'Cup', aliases: ['kop', 'tazza', 'becher'] },
  { theme: 'Cupcake', aliases: ['briosa', 'muffin', 'babeczka', 'кекс'] },
  { theme: 'Curtain', aliases: ['tenda'] },
  { theme: 'Cutting Board', aliases: ['tagliere'] },
  { theme: 'Cyborg', aliases: ['robot'] },
  { theme: 'Cyclops' },
  { theme: 'Dad', aliases: ['pai', 'apa', 'far', 'baba', 'vader'] },
  { theme: 'Daffodil', aliases: ['narci'] },
  { theme: 'Dagger', aliases: ['tor', 'kilic', 'dagger', '匕首'] },
  { theme: 'Date' },
  { theme: 'Day', aliases: ['zi', 'tag', 'dag', 'nap'] },
  { theme: 'Dead Tree' },
  { theme: 'Deer' },
  { theme: 'Demon', aliases: ['seytan', '악마'] },
  { theme: 'Dentist', aliases: ['disci'] },
  { theme: 'Desert', aliases: ['col', 'desert'] },
  { theme: 'Desk', aliases: ['masa', 'mesa', 'birou', 'bureau', 'tavolo', 'tyopoyta', 'escritorio', '桌子', 'стол', 'стіл'] },
  { theme: 'Dessert', aliases: ['deser', 'desert'] },
  { theme: 'Devil', aliases: ['seytan', '악마'] },
  { theme: 'Diamond', aliases: ['elma', 'jewel'] },
  { theme: 'Diamond Ring' },
  { theme: 'Dice', aliases: ['de', 'kostka', 'wurfel', 'terning'] },
  { theme: 'Dinner', aliases: ['repa', 'cina', 'обед'] },
  { theme: 'Dinosaur', aliases: ['dinozor'] },
  { theme: 'Diploma', aliases: ['diplom'] },
  { theme: 'Dirt House', aliases: ['erdhau'] },
  { theme: 'Disco' },
  { theme: 'Disco Ball', aliases: ['discobal'] },
  { theme: 'Dish', aliases: ['fad', 'bord', 'prato', 'plato', 'piatto', 'farfurie', '皿', '盘子', '盤子', '접시'] },
  { theme: 'Dishwasher', aliases: ['zmywarka'] },
  { theme: 'Dispenser', aliases: ['ejetor', 'automat'] },
  { theme: 'Diving Board', aliases: ['vippe', 'trampolin'] },
  { theme: 'DNA' },
  { theme: 'Dock', aliases: ['dok', 'molo', 'satama', '码头', '碼頭'] },
  { theme: 'Doctor', aliases: ['orvo'] },
  { theme: 'Dodgeball', aliases: ['kidobos'] },
  { theme: 'Dog', aliases: ['pe', 'pie', 'pes', 'cane', 'cachorro'] },
  { theme: 'Dog Collar', aliases: ['obojek'] },
  { theme: 'Doll', aliases: ['pop', 'dukke'] },
  { theme: 'Dollar', aliases: ['dolar'] },
  { theme: 'Dollhouse', aliases: ['dockhu'] },
  { theme: 'Dolphin', aliases: ['yunu'] },
  { theme: 'Domino' },
  { theme: 'Donkey', aliases: ['ane', 'burro'] },
  { theme: 'Donut', aliases: ['dona'] },
  { theme: 'Door', aliases: ['usa', 'porte', 'puerta', '門'] },
  { theme: 'Door Knob', aliases: ['kilinc'] },
  { theme: 'Dove', aliases: ['due', 'duif', 'duva', 'golab', 'taube', 'galamb', 'paloma', 'porumbel', 'guvercin', 'ハト', '鴿子', '鸽子', '비둘기', 'голуб', 'голубь'] },
  { theme: 'Dragon', aliases: ['drak', 'drake', 'drage'] },
  { theme: 'Dragon Egg', aliases: ['drakagg'] },
  { theme: 'Dragonfly', aliases: ['libel'] },
  { theme: 'Drawing', aliases: ['rajz', '그림'] },
  { theme: 'Dress', aliases: ['abito'] },
  { theme: 'Drink', aliases: ['ital', 'drankje'] },
  { theme: 'Driveway', aliases: ['alee', 'дорога', 'garagem'] },
  { theme: 'Drum', aliases: ['dob', 'drum'] },
  { theme: 'Drum Sticks', aliases: ['baget'] },
  { theme: 'Duck' },
  { theme: 'Dumbbell', aliases: ['pesa'] },
  { theme: 'Dungeon', aliases: ['tyrma', 'masmorra'] },
  { theme: 'DVD' },
  { theme: 'Dwarf', aliases: ['cuce', 'trpaslik', 'гном'] },
  { theme: 'Dynamite', aliases: ['tnt', 'dynamit', 'dinamite', 'dynamite', 'динамит', 'динаміт'] },
  { theme: 'Eagle', aliases: ['sa', 'sas', 'vultur', '독수리'] },
  { theme: 'Ear', aliases: ['ora'] },
  { theme: 'Earring', aliases: ['kupe'] },
  { theme: 'Earth', aliases: ['erde', 'terre', 'tierra', '地球'] },
  { theme: 'Easter', aliases: ['pask'] },
  { theme: 'Easter Bunny', aliases: ['paashaa'] },
  { theme: 'Easter Egg', aliases: ['paasei'] },
  { theme: 'Eel', aliases: ['al'] },
  { theme: 'Eggplant', aliases: ['lilek'] },
  { theme: 'Eggs' },
  { theme: 'Egypt', aliases: ['misir'] },
  { theme: 'Elbow', aliases: ['cot'] },
  { theme: 'Electric Keyboard' },
  { theme: 'Elephant', aliases: ['slon'] },
  { theme: 'Elevator', aliases: ['his'] },
  { theme: 'Elf', aliases: ['精灵', '精靈'] },
  { theme: 'Emerald', aliases: ['zumrut'] },
  { theme: 'Emoji', aliases: ['смайлик'] },
  { theme: 'Enchant', aliases: ['buyu'] },
  { theme: 'Ender Dragon', aliases: ['drakzendu'] },
  { theme: 'Enderman' },
  { theme: 'England', aliases: ['anglia', '영국'] },
  { theme: 'Envelope', aliases: ['plic'] },
  { theme: 'Environment', aliases: ['mediu'] },
  { theme: 'Eraser', aliases: ['gum', 'гумка', 'guma', 'gomma', 'gomme'] },
  { theme: 'Escalator', aliases: ['roltrap'] },
  { theme: 'Europe' },
  { theme: 'Exit' },
  { theme: 'Experiment', aliases: ['deney'] },
  { theme: 'Explosion', aliases: ['patlama'] },
  { theme: 'Eye', aliases: ['눈'] },
  { theme: 'Eye Patch', aliases: ['pala', 'palas'] },
  { theme: 'Eyebrow', aliases: ['kas'] },
  { theme: 'Face', aliases: ['arc', 'fata', 'cara'] },
  { theme: 'Factory', aliases: ['gyar'] },
  { theme: 'Fair', aliases: ['vidampark'] },
  { theme: 'Fairy', aliases: ['fe', 'vila', 'fata'] },
  { theme: 'Family', aliases: ['aile'] },
  { theme: 'Fan', aliases: ['fan'] },
  { theme: 'Fang', aliases: ['colt', 'karom'] },
  { theme: 'Farm', aliases: ['gard'] },
  { theme: 'Fashion Show', aliases: ['defile'] },
  { theme: 'Fast Food' },
  { theme: 'Fat', aliases: ['gra'] },
  { theme: 'Feet', aliases: ['pes', 'pie'] },
  { theme: 'Fence', aliases: ['hek', 'cit', 'gard', 'barriere'] },
  { theme: 'Ferris Wheel', aliases: ['noria'] },
  { theme: 'Festival', aliases: ['节日'] },
  { theme: 'Field', aliases: ['mezo'] },
  { theme: 'Fin', aliases: ['pinna', 'pletwa', 'yuzgec', 'ploutev'] },
  { theme: 'Finger', aliases: ['ujj', 'palec', 'vinger'] },
  { theme: 'Finish Line', aliases: ['meta'] },
  { theme: 'Fire', aliases: ['tuz'] },
  { theme: 'Fire Engine', aliases: ['paloauto'] },
  { theme: 'Fire Extinguisher', aliases: ['gasnica'] },
  { theme: 'Fireball', aliases: ['eldklot'] },
  { theme: 'Firefly' },
  { theme: 'Fireplace', aliases: ['krb', 'cheminee', 'chimenea'] },
  { theme: 'Fireworks' },
  { theme: 'First Aid', aliases: ['ensiapu'] },
  { theme: 'Fish', aliases: ['vi', 'hal'] },
  { theme: 'Fish Bowl', aliases: ['fanu', 'aquario', 'akvarium', 'aquarium', 'аквариум', 'акваріум'] },
  { theme: 'Fisherman', aliases: ['rybar', 'pescar'] },
  { theme: 'Fishing', aliases: ['fiske', 'pescar'] },
  { theme: 'Fist', aliases: ['neve'] },
  { theme: 'Flags', aliases: ['flag', '旗', '旗帜', '旗幟'] },
  { theme: 'Flamingo', aliases: ['flaming'] },
  { theme: 'Flare', aliases: ['blus', 'bengala'] },
  { theme: 'Flashlight', aliases: ['torcia', 'lanterna', 'linterna'] },
  { theme: 'Flipper', aliases: ['palme', 'pinna', 'pletwa', 'yuzgec', 'ploutev'] },
  { theme: 'Floating Island', aliases: ['ucan ada'] },
  { theme: 'Flood', aliases: ['sel'] },
  { theme: 'Floor', aliases: ['gulv', 'piano'] },
  { theme: 'Flowerpot', aliases: ['maceta'] },
  { theme: 'Flowers', aliases: ['fleur'] },
  { theme: 'Flute', aliases: ['flut', 'fløjte', 'fløyte'] },
  { theme: 'Fly', aliases: ['fliege'] },
  { theme: 'Flying Pig' },
  { theme: 'Folder', aliases: ['map', 'mappa', 'pasta'] },
  { theme: 'Food', aliases: ['mad'] },
  { theme: 'Football', aliases: ['foci', 'soccer', 'futbol', 'fotboll', 'football', 'jalkapallo', '足球', 'футбол'] },
  { theme: 'Football field' },
  { theme: 'Football Helmet', aliases: ['focissisak'] },
  { theme: 'Footprint', aliases: ['stopa'] },
  { theme: 'Forehead', aliases: ['otsa', 'panna', 'panne', 'pande', 'testa'] },
  { theme: 'Forest', aliases: ['la', 'le', 'las', 'orman'] },
  { theme: 'Forest Fire', aliases: ['erdotuz'] },
  { theme: 'Fortress', aliases: ['kale', 'крепость', 'festung', 'twierdza', 'linnoitu', 'fortaleza', 'forteresse', '要塞', 'фортеця'] },
  { theme: 'Fortune Cookie', aliases: ['lykkekake'] },
  { theme: 'Fossil', aliases: ['fosil'] },
  { theme: 'Fountain', aliases: ['fonte', 'fantana'] },
  { theme: 'Fox', aliases: ['li'] },
  { theme: 'Frame', aliases: ['ram', 'quadro', 'moldura', 'cornice'] },
  { theme: 'Frankenstein' },
  { theme: 'French Fries', aliases: ['chips', 'pomme', 'batatafrita', 'patatasfritas', 'batatasfritas'] },
  { theme: 'Fridge', aliases: ['fridge', 'nevera', 'lodowka', 'kylskap', 'lednice', 'koelkast', 'frigider', 'jaakaappi', 'buzdolabi', 'frigorifero', 'frigorifico', 'kuhlschrank', 'hutoszekreny', 'refrigerateur', '冰箱', '冷蔵庫', '냉장고', 'køleskab', 'kjøleskap', 'холодильник'] },
  { theme: 'Frisbee', aliases: ['frisbi'] },
  { theme: 'Frog', aliases: ['жаба', 'sapo', 'kurbaga'] },
  { theme: 'Frown' },
  { theme: 'Fruit', aliases: ['owoc'] },
  { theme: 'Fruit Basket', aliases: ['obstkorb'] },
  { theme: 'Fruit Punch', aliases: ['ponch'] },
  { theme: 'Frying pan', aliases: ['tava', 'panev', 'sarten', 'padella', 'patelnia', 'serpenyo', '平底鍋', '프라이팬', 'сковорода'] },
  { theme: 'Fudge' },
  { theme: 'Fur', aliases: ['pelo'] },
  { theme: 'Furnace', aliases: ['ovn', 'firin', 'печь', 'four', 'ofen', 'piec', 'oven', 'uuni', 'horno', 'cuptor'] },
  { theme: 'Furniture', aliases: ['butor'] },
  { theme: 'Galaxy', aliases: ['galax', '銀河'] },
  { theme: 'Gallery', aliases: ['galeri'] },
  { theme: 'Game', aliases: ['gra', 'jogo', 'jatek'] },
  { theme: 'Games Controller', aliases: ['controller', 'spelkontroll', 'oyunkumandasi'] },
  { theme: 'Gaming Chair', aliases: ['gamerszek'] },
  { theme: 'Garage', aliases: ['garaj', 'garagem'] },
  { theme: 'Garbage Can', aliases: ['lixeira', 'poubelle', 'mulleimer', 'cop kutusu', 'skraldespand', 'ゴミ箱', '垃圾桶', '쓰레기통', 'мусорноеведро', 'vuilnisbak', 'cos de gunoi', 'odpadkovy kos', 'caixotedolixo', 'смітник'] },
  { theme: 'Garbage Truck', aliases: ['sopbil'] },
  { theme: 'Garden', aliases: ['hage'] },
  { theme: 'Garlic Bread', aliases: ['pandeajo'] },
  { theme: 'Gates', aliases: ['port', 'gate', 'porte', 'puerta', 'portar', '門', 'ворота'] },
  { theme: 'Genie', aliases: ['cin', '精灵', '精靈'] },
  { theme: 'Genie Lamp', aliases: ['lampa', 'lampas'] },
  { theme: 'Ghast', aliases: ['das'] },
  { theme: 'Giant', aliases: ['reu', 'kjempe'] },
  { theme: 'Gift', aliases: ['gift', 'gave', 'cadou', 'hediye', 'regalo', 'cadeau', 'ajandek', 'present', 'presente', 'geschenk', '礼物', '禮物', '선물', 'подарок', 'подарунок'] },
  { theme: 'Gingerbread Man', aliases: ['kagemand'] },
  { theme: 'Giraffe', aliases: ['giraf'] },
  { theme: 'Girl', aliases: ['kiz', 'fata'] },
  { theme: 'Glass', aliases: ['gla', 'glas', 'sticla'] },
  { theme: 'Glass of Milk', aliases: ['glasmelk'] },
  { theme: 'Glasses', aliases: ['bril', 'brille', 'occhiali', 'очки', 'окуляри'] },
  { theme: 'Globe', aliases: ['kure', 'sfera', 'globo', '地球'] },
  { theme: 'Gloves', aliases: ['luva', 'guanti'] },
  { theme: 'Glue', aliases: ['lim', 'cola'] },
  { theme: 'Gnome', aliases: ['cuce', 'trpaslik', 'гном'] },
  { theme: 'Goal', aliases: ['mal', 'tor', 'gol', 'kapu', 'maali', 'ворота'] },
  { theme: 'Goalkeeper', aliases: ['kapu', 'portar'] },
  { theme: 'Goat', aliases: ['get', 'koza'] },
  { theme: 'Goblin', aliases: ['hiisi', 'duende', 'kobold'] },
  { theme: 'Godzilla' },
  { theme: 'Goggles', aliases: ['bril', 'brille', 'occhiali', 'очки', 'окуляри'] },
  { theme: 'Gold', aliases: ['or', 'ors'] },
  { theme: 'Gold Medal' },
  { theme: 'Gold Mine' },
  { theme: 'Gold Ring' },
  { theme: 'Golden Apple', aliases: ['gulleple'] },
  { theme: 'Goldfish', aliases: ['goudvi'] },
  { theme: 'Golem', aliases: ['kjempe'] },
  { theme: 'Golf Ball', aliases: ['golfbal'] },
  { theme: 'Golf Cart', aliases: ['golfkar'] },
  { theme: 'Golf Club', aliases: ['golfuto'] },
  { theme: 'Golf Course', aliases: ['golfbane'] },
  { theme: 'Goose', aliases: ['oca'] },
  { theme: 'Gorilla', aliases: ['goril'] },
  { theme: 'Grapes', aliases: ['uva'] },
  { theme: 'Graph', aliases: ['graf'] },
  { theme: 'Grappling Hook', aliases: ['hak'] },
  { theme: 'Grasshopper', aliases: ['lacusta'] },
  { theme: 'Gravel', aliases: ['gru', 'sterk'] },
  { theme: 'Graveyard', aliases: ['temeto'] },
  { theme: 'Great Britain', aliases: ['영국'] },
  { theme: 'Green', aliases: ['gron'] },
  { theme: 'Greenhouse', aliases: ['sera', 'serra', 'estufa'] },
  { theme: 'Griffin', aliases: ['grif'] },
  { theme: 'Grim Reaper', aliases: ['kaszas', 'ceifador', 'mietitore', 'liemannen', 'viikatemie', 'sensenmann', 'mandenmedleen', '死神', 'døden', 'жнець'] },
  { theme: 'Guardian', aliases: ['orzo'] },
  { theme: 'Guitar', aliases: ['gitar'] },
  { theme: 'Gum', aliases: ['гумка', 'gum', 'guma', 'gomma', 'gomme', 'chicle', 'kaugummi', 'pastilha elastica'] },
  { theme: 'Gumball', aliases: ['chicle', 'kaugummi', 'pastilha elastica'] },
  { theme: 'Gym', aliases: ['sala'] },
  { theme: 'Hair', aliases: ['haj', 'sac', 'pelo'] },
  { theme: 'Hair Band', aliases: ['tiara', 'bandana'] },
  { theme: 'Hairbrush', aliases: ['kam', 'perie', 'escova', '梳子', 'расчёска'] },
  { theme: 'Haircut', aliases: ['uces'] },
  { theme: 'Halloween' },
  { theme: 'Hallway', aliases: ['flur', 'corredor'] },
  { theme: 'Halo', aliases: ['hale'] },
  { theme: 'Ham' },
  { theme: 'Hamburger', aliases: ['hamburger', 'hamburguer', 'hamburguesa', 'hampurilainen', '漢堡', 'ハンバーガー'] },
  { theme: 'Hammer', aliases: ['hamer'] },
  { theme: 'Hammock', aliases: ['hamak'] },
  { theme: 'Hamster', aliases: ['krecek'] },
  { theme: 'Handbag', aliases: ['veske', 'borsa', 'geanta', 'torebka', '手提包', 'сумка'] },
  { theme: 'Handcuffs', aliases: ['pouta'] },
  { theme: 'Handshake', aliases: ['kattely'] },
  { theme: 'Handstand', aliases: ['stojka'] },
  { theme: 'Hanggliding', aliases: ['planare'] },
  { theme: 'Happy', aliases: ['glad'] },
  { theme: 'Harbor', aliases: ['cai', 'port', 'satama'] },
  { theme: 'Hard Hat', aliases: ['kask', 'capacete', 'ヘルメット'] },
  { theme: 'Harp', aliases: ['arp'] },
  { theme: 'Hat', aliases: ['cepice', '모자', 'hut', 'sapka'] },
  { theme: 'Hay', aliases: ['ho', 'hő', 'fan', 'høy'] },
  { theme: 'Head', aliases: ['cap', 'kopf', 'testa', 'cabeza'] },
  { theme: 'Headband', aliases: ['venda', 'bandana'] },
  { theme: 'Headphones', aliases: ['casti', 'kulaklik', 'ecouteur', 'sluchatka', 'kuulokkeet', 'fejhallgato', 'koptelefoon', '耳机', '耳機', 'наушники'] },
  { theme: 'Headset', aliases: ['cuffie', 'kulaklik', 'ecouteur', 'sluchatka', 'kuulokkeet', 'fejhallgato', 'koptelefoon', '耳机', '耳機', 'наушники'] },
  { theme: 'Heart', aliases: ['hart'] },
  { theme: 'Hedge', aliases: ['cit', 'haie', 'hekk', 'arbusto'] },
  { theme: 'Hedgehog', aliases: ['jez'] },
  { theme: 'Helicopter', aliases: ['elicopter'] },
  { theme: 'Helipad' },
  { theme: 'Helmet', aliases: ['kask', '모자', 'capacete', 'ヘルメット'] },
  { theme: 'Hen', aliases: ['kana', 'tavuk', 'gallina', 'galinha', 'курка', 'курица'] },
  { theme: 'Hero', aliases: ['hos', 'hő'] },
  { theme: 'Hexagon' },
  { theme: 'Hide and Seek', aliases: ['saklambac'] },
  { theme: 'High Heels', aliases: ['szpilki'] },
  { theme: 'Highway', aliases: ['otoyol', 'дорога'] },
  { theme: 'Hill' },
  { theme: 'Hippopotamus', aliases: ['hippo'] },
  { theme: 'Hockey', aliases: ['hokey'] },
  { theme: 'Hockey Rink' },
  { theme: 'Hog', aliases: ['porc', 'domuz', 'cerdo', 'maiale', 'schwein', '猪', '豬', 'ブタ', '돼지'] },
  { theme: 'Hole', aliases: ['hal', 'kolo', '洞穴'] },
  { theme: 'Holiday', aliases: ['jul', 'natal', 'joulu', 'karacsony', '节日', 'свято'] },
  { theme: 'Holiday Lights', aliases: ['julely'] },
  { theme: 'Hollywood Sign' },
  { theme: 'Homework', aliases: ['teme'] },
  { theme: 'Honey', aliases: ['mel', 'miel'] },
  { theme: 'Honeycomb', aliases: ['panal', 'alveare', '蜂窩'] },
  { theme: 'Hook', aliases: ['hak', 'krog'] },
  { theme: 'Horn', aliases: ['rog', 'roh', 'horn', '喇叭'] },
  { theme: 'Horse', aliases: ['lo'] },
  { theme: 'Horse Racing', aliases: ['at yarisi'] },
  { theme: 'Hospital', aliases: ['spital'] },
  { theme: 'Hot Air Balloon', aliases: ['luftballon'] },
  { theme: 'Hot Chocolate', aliases: ['kakao'] },
  { theme: 'Hot Dog', aliases: ['hotdog'] },
  { theme: 'Hot Tub', aliases: ['palju', 'banheira', 'whirlpool'] },
  { theme: 'Hotel', aliases: ['inn', '酒店'] },
  { theme: 'Hourglass', aliases: ['timgla', 'hourglas'] },
  { theme: 'House', aliases: ['hu'] },
  { theme: 'Hula Hoop', aliases: ['aro'] },
  { theme: 'Hunter', aliases: ['avci'] },
  { theme: 'Hurdles', aliases: ['haie', 'hekk', 'engel'] },
  { theme: 'Hurricane', aliases: ['orkan'] },
  { theme: 'Hut', aliases: ['小屋', 'хижина', 'hut', 'hutte', 'kulube', 'cabana', 'kunyho', 'capanna', '오두막', 'хатина'] },
  { theme: 'Hypixel' },
  { theme: 'Hypnotize', aliases: ['hypnose'] },
  { theme: 'Ice Age', aliases: ['istid'] },
  { theme: 'Ice Bucket', aliases: ['ishink', 'cubodehielo'] },
  { theme: 'Ice Castle', aliases: ['isslot'] },
  { theme: 'Ice Cream', aliases: ['ei', 'glas', 'gelado'] },
  { theme: 'Ice Cream Cone', aliases: ['isvaffel'] },
  { theme: 'Ice Cream Truck', aliases: ['isbil'] },
  { theme: 'Ice Cube', aliases: ['isbit', 'cubodehielo'] },
  { theme: 'Ice Skates', aliases: ['lyzwy', 'patine', 'schaatsen'] },
  { theme: 'Ice Spike', aliases: ['ispigg', 'jegcsap', 'rampouch', 'estalactite'] },
  { theme: 'Iceberg', aliases: ['isberg'] },
  { theme: 'Icicle', aliases: ['sopel', 'jegcsap', 'rampouch', 'estalactite'] },
  { theme: 'Icy', aliases: ['gele', 'gelado'] },
  { theme: 'Igloo', aliases: ['iglo'] },
  { theme: 'Illusion', aliases: ['iluze'] },
  { theme: 'Ink', aliases: ['tinta'] },
  { theme: 'Insect', aliases: ['owad', 'bocek', 'insekt', 'inseto', 'insect', 'insetto', 'insecte', 'insecto'] },
  { theme: 'Instrument', aliases: ['nastroj'] },
  { theme: 'Iron', aliases: ['va'] },
  { theme: 'Ironing Board', aliases: ['bugelbrett'] },
  { theme: 'Jacket', aliases: ['ja', 'jacke', 'takki', 'casaco'] },
  { theme: 'Jail', aliases: ['prisao', 'prison', 'borton', 'vezeni', 'fengsel', 'vankila', 'fangelse', 'prigione', 'gefangnis', 'wiezienie', 'gevangeni', '监狱', '監獄', '감옥', 'тюрьма', 'fængsel', 'в\'язниця'] },
  { theme: 'Janitor', aliases: ['pedel'] },
  { theme: 'Japan' },
  { theme: 'Jar', aliases: ['glas', 'gla', 'burk', '瓶', 'банка'] },
  { theme: 'Jeans' },
  { theme: 'Jelly', aliases: ['gele'] },
  { theme: 'Jellybeans', aliases: ['goma'] },
  { theme: 'Jellyfish', aliases: ['kwal'] },
  { theme: 'Jet Ski', aliases: ['motoscafo'] },
  { theme: 'Jetpack' },
  { theme: 'Jewellery', aliases: ['sperky'] },
  { theme: 'Jigsaw', aliases: ['sega', 'yapboz', 'pussel', 'puzzle', 'puzzel', 'palapeli', 'ukladanka', 'puslespil', 'puslespill', '拼圖', 'пазл', 'quebra-cabeça'] },
  { theme: 'Jogging', aliases: ['kosu', 'behani', 'corrida'] },
  { theme: 'Joystick' },
  { theme: 'Juggling' },
  { theme: 'Juice', aliases: ['ju', 'sumo'] },
  { theme: 'Jump Rope', aliases: ['hopprep'] },
  { theme: 'Jumping', aliases: ['ugras'] },
  { theme: 'Jungle', aliases: ['orman'] },
  { theme: 'Kangaroo', aliases: ['kangur'] },
  { theme: 'Karaoke' },
  { theme: 'Karate' },
  { theme: 'Kayak', aliases: ['kajak', 'kayak'] },
  { theme: 'Kelp', aliases: ['alga', 'tang', 'algue', 'hinar', 'seetang', 'zeewier', 'merileva', 'водоросли'] },
  { theme: 'Kennel', aliases: ['hok', 'buda', 'bouda'] },
  { theme: 'Ketchup', aliases: ['kecup', 'ketcap', 'keczup', 'ketchup', '番茄酱', '番茄醬', 'кетчуп'] },
  { theme: 'Kettle', aliases: ['kedel', 'tetera', 'чайник'] },
  { theme: 'Key' },
  { theme: 'Keyboard', aliases: ['klavye'] },
  { theme: 'Kid', aliases: ['barn', 'dziecko', 'bambino', 'дитина', 'ребёнок'] },
  { theme: 'King', aliases: ['re', 'rei'] },
  { theme: 'Kiss', aliases: ['ku', 'kus', 'kis'] },
  { theme: 'Kitchen', aliases: ['kok', 'cocina', 'cucina', 'cuisine'] },
  { theme: 'Kite', aliases: ['drake', 'drage', 'cometa'] },
  { theme: 'Kitten', aliases: ['kote', '고양이'] },
  { theme: 'Kiwi Fruit', aliases: ['kivi'] },
  { theme: 'Knee', aliases: ['kne'] },
  { theme: 'Knife', aliases: ['me', 'dagger', '匕首'] },
  { theme: 'Knight', aliases: ['rytir'] },
  { theme: 'Koala' },
  { theme: 'Label', aliases: ['eticheta', 'etiqueta', 'etiquette'] },
  { theme: 'Laboratory', aliases: ['labor'] },
  { theme: 'Ladder', aliases: ['letra', 'stege', 'tikkaat', 'escalera', 'merdiven', 'драбина', 'лестница'] },
  { theme: 'Ladybug' },
  { theme: 'Lake', aliases: ['to', 'gol', 'lago'] },
  { theme: 'Lamb', aliases: ['lam', 'miel', 'barany'] },
  { theme: 'Lamp', aliases: ['lampas', 'lampa', 'lampada', '등불'] },
  { theme: 'Lamp Post', aliases: ['lampione', 'lampadaire', 'postedeluz', 'фонарныйстолб'] },
  { theme: 'Lampshade', aliases: ['klosz', 'pantalla'] },
  { theme: 'Lantern', aliases: ['lykta', 'lampas', 'lanterna', 'linterna', 'latarnia', '등불'] },
  { theme: 'Laptop' },
  { theme: 'Laser' },
  { theme: 'Laundry Basket', aliases: ['wasmand'] },
  { theme: 'Lava', aliases: ['lav', 'lava', 'lave'] },
  { theme: 'Lava Bucket', aliases: ['lavahink'] },
  { theme: 'Lava Lamp' },
  { theme: 'Lawn Games', aliases: ['havespil'] },
  { theme: 'Lawn Mower', aliases: ['sekacka'] },
  { theme: 'Lawyer', aliases: ['avocat'] },
  { theme: 'Leaf', aliases: ['lov', 'hoja', 'folha', 'level', 'blad', 'list', 'blatt', 'feuille', '葉', 'листва'] },
  { theme: 'Leaking roof', aliases: ['lekkenddak'] },
  { theme: 'Leather', aliases: ['bor'] },
  { theme: 'Leaves', aliases: ['lov', 'hoja', 'folha', 'feuille', '葉', 'листва'] },
  { theme: 'Lecture Hall', aliases: ['aula'] },
  { theme: 'Leg' },
  { theme: 'Lemon', aliases: ['limao'] },
  { theme: 'Lemonade', aliases: ['lemonad', 'limonade'] },
  { theme: 'Lemonade Stand', aliases: ['lemonadkiosk'] },
  { theme: 'Leprechaun', aliases: ['cin', '精灵', 'duende', 'kobold'] },
  { theme: 'Letter', aliases: ['list', 'level', 'carta', 'лист'] },
  { theme: 'Lettuce', aliases: ['sla', 'salat', 'sallad', 'salata', 'salade', 'салат'] },
  { theme: 'Librarian' },
  { theme: 'Library', aliases: ['knihovna', 'bibliotheque', 'librărie'] },
  { theme: 'Lifejacket', aliases: ['livvast'] },
  { theme: 'Light', aliases: ['ly', 'leve', 'swiatlo'] },
  { theme: 'Light Switch', aliases: ['lysbryter', 'interruptor', 'interrupteur'] },
  { theme: 'Lightbulb', aliases: ['bec', 'lampada'] },
  { theme: 'Lighthouse', aliases: ['fyr'] },
  { theme: 'Lightning Strike', aliases: ['raio', 'relampago'] },
  { theme: 'Lightsaber', aliases: ['fenykard'] },
  { theme: 'Lilypad', aliases: ['nufar'] },
  { theme: 'Lime', aliases: ['limao'] },
  { theme: 'Line', aliases: ['cara', 'linha', '線', '线'] },
  { theme: 'Lion', aliases: ['lew'] },
  { theme: 'Lips', aliases: ['usta'] },
  { theme: 'Lipstick', aliases: ['ruj'] },
  { theme: 'Litter', aliases: ['cop', 'lixo', 'basura', 'skrap', 'gunoi', 'szemet', 'smieci', '垃圾', '쓰레기', 'мусор', 'søppel', 'сміття'] },
  { theme: 'Living room' },
  { theme: 'Lizard', aliases: ['odla'] },
  { theme: 'Llama', aliases: ['lama'] },
  { theme: 'Loaf of Bread', aliases: ['brood'] },
  { theme: 'Lobby', aliases: ['port'] },
  { theme: 'Lobster', aliases: ['humr'] },
  { theme: 'Lock', aliases: ['las', 'slot', 'zamek', 'fechadura', '鎖', 'lå', 'замок'] },
  { theme: 'Lock Pick', aliases: ['dyrk', 'fechadura'] },
  { theme: 'Log', aliases: ['stock', 'træ'] },
  { theme: 'Log Cabin', aliases: ['srub', 'хижина', 'fahaz', 'trehytte'] },
  { theme: 'Lollipop', aliases: ['lolly', 'acadea'] },
  { theme: 'London' },
  { theme: 'Lucky Block' },
  { theme: 'Luggage', aliases: ['bavul'] },
  { theme: 'Lumberjack', aliases: ['drwal'] },
  { theme: 'Lunch', aliases: ['obed', 'frokost', 'обед'] },
  { theme: 'Lunchbox', aliases: ['matbok'] },
  { theme: 'Machine', aliases: ['kone', 'stroj'] },
  { theme: 'Magazine', aliases: ['blad', 'magazin', 'magazyn'] },
  { theme: 'Magic', aliases: ['buyu', 'magico'] },
  { theme: 'Magic Carpet', aliases: ['taikamatto'] },
  { theme: 'Magic Hat', aliases: ['joben'] },
  { theme: 'Magic Wand', aliases: ['taikasauva', 'zauberstab', 'tryllestav', 'bagheta magica', 'varinha magica', 'baguettemagique', 'bacchettamagica', 'волшебнаяпалочка'] },
  { theme: 'Magician', aliases: ['mago', 'magico', 'magicien', 'sihirbaz', 'волшебник'] },
  { theme: 'Magma Cube', aliases: ['magmakub'] },
  { theme: 'Magnet', aliases: ['ima'] },
  { theme: 'Magnifying Glass', aliases: ['lupa'] },
  { theme: 'Mail', aliases: ['level', 'postá', 'post', 'posta', 'postas', 'poczta', 'correio', 'почта'] },
  { theme: 'Mailbox', aliases: ['buzon'] },
  { theme: 'Mailman', aliases: ['postas', 'postá'] },
  { theme: 'Makeup', aliases: ['smink'] },
  { theme: 'Mammoth', aliases: ['mamut', '거대한'] },
  { theme: 'Mannequin', aliases: ['model'] },
  { theme: 'Mansion', aliases: ['vila', 'palac', 'villa', 'kastely'] },
  { theme: 'Map', aliases: ['map', 'kort', 'mappa', 'carte'] },
  { theme: 'Marbles', aliases: ['bille'] },
  { theme: 'Marker', aliases: ['fix', 'marcador'] },
  { theme: 'Market', aliases: ['trh', 'market'] },
  { theme: 'Mars', aliases: ['mar'] },
  { theme: 'Marshmallow', aliases: ['bezea', '棉花糖'] },
  { theme: 'Mask', aliases: ['mask'] },
  { theme: 'Matchstick', aliases: ['gyufa'] },
  { theme: 'Mathematics', aliases: ['math'] },
  { theme: 'Mattress', aliases: ['patja'] },
  { theme: 'Mayonnaise', aliases: ['mayo'] },
  { theme: 'Maze' },
  { theme: 'Meadow', aliases: ['eng', 'prato', 'mezo'] },
  { theme: 'Measurement', aliases: ['mal', 'maling'] },
  { theme: 'Meatball', aliases: ['kofte'] },
  { theme: 'Mechanic', aliases: ['gepesz'] },
  { theme: 'Medieval House', aliases: ['ortacag evi'] },
  { theme: 'Meeting', aliases: ['mote'] },
  { theme: 'Mermaid', aliases: ['sello'] },
  { theme: 'Meteorite', aliases: ['goktasi'] },
  { theme: 'Mexico', aliases: ['mexic'] },
  { theme: 'Microphone', aliases: ['microfon'] },
  { theme: 'Microwave', aliases: ['mikro'] },
  { theme: 'Milk' },
  { theme: 'Milkshake', aliases: ['batido'] },
  { theme: 'Milky Way', aliases: ['tejut', '銀河'] },
  { theme: 'Mine', aliases: ['dul', 'kaivo', '挖矿', '挖礦', 'шахта'] },
  { theme: 'Minecart', aliases: ['lore', 'vozik', 'vagon', 'carrinhodemina'] },
  { theme: 'Minecraft' },
  { theme: 'Miner' },
  { theme: 'Mineshaft', aliases: ['шахта'] },
  { theme: 'Mini Golf' },
  { theme: 'Mining', aliases: ['挖矿', '挖礦'] },
  { theme: 'Minotaur' },
  { theme: 'Mirror', aliases: ['ayna'] },
  { theme: 'Missile', aliases: ['fuze', 'raket', 'ракета', 'raketa', 'rakete', 'rakieta'] },
  { theme: 'Mittens', aliases: ['luva', 'guanti'] },
  { theme: 'Moat' },
  { theme: 'Modern Art' },
  { theme: 'Modern House', aliases: ['modernev'] },
  { theme: 'Mole', aliases: ['mol', 'topo'] },
  { theme: 'Mom', aliases: ['mor'] },
  { theme: 'Money', aliases: ['para', 'dinero', 'dinheiro', 'pieniadze'] },
  { theme: 'Monitor', aliases: ['ecran', 'skjerm', 'bildschirm', 'skærm'] },
  { theme: 'Monocle', aliases: ['ooggla'] },
  { theme: 'Monsters', aliases: ['mostri', 'monster'] },
  { theme: 'Moon', aliases: ['ay', 'mond'] },
  { theme: 'Moose', aliases: ['lo'] },
  { theme: 'Mop' },
  { theme: 'Morning', aliases: ['aamu'] },
  { theme: 'Moth', aliases: ['mot', 'mariposa'] },
  { theme: 'Motorcycle', aliases: ['moto'] },
  { theme: 'Mountain', aliases: ['dag'] },
  { theme: 'Mouse', aliases: ['mu', 'topo', 'rato', 'raton', '老鼠'] },
  { theme: 'Mouse Pad', aliases: ['mousepad'] },
  { theme: 'Mousepad', aliases: ['mauspad', 'mousepad'] },
  { theme: 'Mousetrap', aliases: ['ratoeira'] },
  { theme: 'Moustache', aliases: ['bart', 'ひげ'] },
  { theme: 'Mouth', aliases: ['suu', 'usta', 'mond'] },
  { theme: 'Movie', aliases: ['film'] },
  { theme: 'Movie Theatre', aliases: ['cine', 'mozi', 'kino', 'cinema', 'biograf', 'bioscoop', 'elokuvateatteri', '电影院', '電影院', 'кінотеатр'] },
  { theme: 'Mud', aliases: ['lama'] },
  { theme: 'Muffin', aliases: ['kek', 'briosa', 'muffin', 'babeczka', 'кекс'] },
  { theme: 'Mug', aliases: ['kop', 'tazza', 'becher'] },
  { theme: 'Mummy' },
  { theme: 'Muscle', aliases: ['ka', 'kas'] },
  { theme: 'Museum', aliases: ['muze'] },
  { theme: 'Mushroom', aliases: ['pilz', 'svamp'] },
  { theme: 'Music', aliases: ['zene', 'musik', 'musiikki', '音乐', '음악', 'музика', 'музыка'] },
  { theme: 'Musical', aliases: ['musik', 'musiikki', '音乐', '음악', 'музика', 'музыка'] },
  { theme: 'Musician', aliases: ['musico'] },
  { theme: 'Mustard', aliases: ['senf'] },
  { theme: 'Nachos' },
  { theme: 'Nail polish', aliases: ['oje'] },
  { theme: 'Name Tag', aliases: ['cedula', 'eticheta', 'etiqueta', 'etiquette'] },
  { theme: 'Napkin', aliases: ['serviett', 'servetel', 'serviette'] },
  { theme: 'Narwhal', aliases: ['narwal'] },
  { theme: 'Nature', aliases: ['doga'] },
  { theme: 'Necklace', aliases: ['colar', 'ketting'] },
  { theme: 'Needle', aliases: ['tu', 'acs', 'nadel', '針'] },
  { theme: 'Nether' },
  { theme: 'Newspaper', aliases: ['avi'] },
  { theme: 'Night', aliases: ['yo'] },
  { theme: 'Nightmare', aliases: ['kabu'] },
  { theme: 'Ninja' },
  { theme: 'Northern Lights', aliases: ['norly'] },
  { theme: 'Notepad' },
  { theme: 'Nurse' },
  { theme: 'Nutcracker', aliases: ['louskacek'] },
  { theme: 'Oar' },
  { theme: 'Oasis', aliases: ['oa', 'vaha'] },
  { theme: 'Ocean', aliases: ['hav'] },
  { theme: 'Ocelot' },
  { theme: 'Octagon' },
  { theme: 'Octopus', aliases: ['polvo', 'kraken', 'poulpe', 'inktvi', 'blackfisk', 'blekksprut', 'blæksprutte'] },
  { theme: 'Office', aliases: ['ofi', 'birou', 'bureau', 'oficina', 'escritorio'] },
  { theme: 'Ogre', aliases: ['ogr'] },
  { theme: 'Oil', aliases: ['ol'] },
  { theme: 'Olympics' },
  { theme: 'Omelette', aliases: ['omlet'] },
  { theme: 'Onesie', aliases: ['pijama'] },
  { theme: 'Onion Ring', aliases: ['lokring'] },
  { theme: 'Orange' },
  { theme: 'Orange Juice', aliases: ['narancsle'] },
  { theme: 'Orchard', aliases: ['sad'] },
  { theme: 'Orchid' },
  { theme: 'Ore' },
  { theme: 'Ornament', aliases: ['sus'] },
  { theme: 'Ostrich', aliases: ['strud'] },
  { theme: 'Otter', aliases: ['oter'] },
  { theme: 'Oven', aliases: ['ovn', 'firin', 'печь', 'four', 'ofen', 'oven', 'uuni', 'horno', 'cuptor'] },
  { theme: 'Owl', aliases: ['sova'] },
  { theme: 'Oyster', aliases: ['ostra'] },
  { theme: 'Packet', aliases: ['pakke'] },
  { theme: 'Paint', aliases: ['mala', 'quadro', 'tinta', 'maali', 'maling', 'pintura'] },
  { theme: 'Paint Bucket', aliases: ['fargburk'] },
  { theme: 'Paint Palette', aliases: ['verfpalet'] },
  { theme: 'Paintball' },
  { theme: 'Paintbrush', aliases: ['ecset', 'pedzel', 'pennello', 'кисть', 'пензель'] },
  { theme: 'Painting', aliases: ['resim', 'quadro', 'pintura', '그림', 'картина'] },
  { theme: 'Palace', aliases: ['palas', 'palac'] },
  { theme: 'Palm tree', aliases: ['palme'] },
  { theme: 'Pan', aliases: ['tava', 'panna', 'panne', 'panev', 'pande', 'sarten', 'padella', 'patelnia', 'serpenyo', '平底鍋', '프라이팬', 'сковорода'] },
  { theme: 'Pancake', aliases: ['crepe'] },
  { theme: 'Panda' },
  { theme: 'Paper', aliases: ['carta'] },
  { theme: 'Paper Airplane', aliases: ['papirfly'] },
  { theme: 'Paperclip', aliases: ['gem'] },
  { theme: 'Parachute', aliases: ['padak'] },
  { theme: 'Park' },
  { theme: 'Parking Lot', aliases: ['parking'] },
  { theme: 'Parkour', aliases: ['parkur'] },
  { theme: 'Parrot', aliases: ['loro'] },
  { theme: 'Party', aliases: ['fest'] },
  { theme: 'Party Hat', aliases: ['festhat'] },
  { theme: 'Pathway', aliases: ['ut', 'pad', 'camino'] },
  { theme: 'Patio', aliases: ['dvur'] },
  { theme: 'Pattern', aliases: ['vzor', 'model', 'monster'] },
  { theme: 'Paws', aliases: ['paw', '爪子'] },
  { theme: 'Pea', aliases: ['arta'] },
  { theme: 'Peach' },
  { theme: 'Peacock', aliases: ['paw'] },
  { theme: 'Peanut', aliases: ['mani'] },
  { theme: 'Peanut Butter', aliases: ['pindakaa'] },
  { theme: 'Pear', aliases: ['para'] },
  { theme: 'Pearl', aliases: ['inci'] },
  { theme: 'Pedals' },
  { theme: 'Pen', aliases: ['kalem', 'penna'] },
  { theme: 'Pencil', aliases: ['penna', 'kalem', 'crayon'] },
  { theme: 'Pencil Case', aliases: ['etui'] },
  { theme: 'Penguin', aliases: ['tucnak'] },
  { theme: 'Pentagon', aliases: ['otszog'] },
  { theme: 'Perfume', aliases: ['parfem'] },
  { theme: 'Pet', aliases: ['pet'] },
  { theme: 'Pet Shop' },
  { theme: 'Pharaoh', aliases: ['farao'] },
  { theme: 'Phoenix', aliases: ['fonix'] },
  { theme: 'Phone Case', aliases: ['cover'] },
  { theme: 'Phone Charger', aliases: ['ladowarka'] },
  { theme: 'Photograph', aliases: ['foto', 'bilde', 'fotograf', 'fotograaf', 'fotografia', '照片', '사진'] },
  { theme: 'Photographer', aliases: ['fotograf', 'fotograaf'] },
  { theme: 'Piano', aliases: ['pian', 'piano', 'klaver'] },
  { theme: 'Pickaxe', aliases: ['pico'] },
  { theme: 'Pickle', aliases: ['picle'] },
  { theme: 'Picnic' },
  { theme: 'Picture', aliases: ['kep', 'quadro', 'foto', 'bilde', 'resim', 'fotografia', '照片', '사진', 'картина'] },
  { theme: 'Picture Frame', aliases: ['moldura', 'cornice'] },
  { theme: 'Pie', aliases: ['pie', 'pai', 'torta', 'taart', 'tarta'] },
  { theme: 'Pier', aliases: ['cai', 'molo', '码头', '碼頭'] },
  { theme: 'Pig', aliases: ['porc', 'domuz', 'cerdo', 'maiale', 'schwein', '猪', '豬', 'ブタ', '돼지'] },
  { theme: 'Pigeon', aliases: ['due', 'duif', 'duva', 'golab', 'taube', 'galamb', 'paloma', 'porumbel', 'guvercin', 'ハト', '鴿子', '鸽子', '비둘기', 'голуб', 'голубь'] },
  { theme: 'Piggy bank', aliases: ['spargri'] },
  { theme: 'Pigman' },
  { theme: 'Pikachu', aliases: ['pikacu'] },
  { theme: 'Pillow', aliases: ['pute'] },
  { theme: 'Pillowcase', aliases: ['fronha'] },
  { theme: 'Pin', aliases: ['tu', 'pin', 'nadel', '針'] },
  { theme: 'Pinata' },
  { theme: 'Pine Tree', aliases: ['pin', 'tall'] },
  { theme: 'Pineapple', aliases: ['pina'] },
  { theme: 'Pineapple Pizza', aliases: ['ananaspizza'] },
  { theme: 'Pinecone', aliases: ['pigna'] },
  { theme: 'Pirate', aliases: ['pirat'] },
  { theme: 'Pirate Hat', aliases: ['pirathat'] },
  { theme: 'Pirate Ship', aliases: ['piratskib'] },
  { theme: 'Piston', aliases: ['pist', 'manta', 'stempel'] },
  { theme: 'Pitchfork', aliases: ['fork', 'tirmik', '갈퀴'] },
  { theme: 'Pizza' },
  { theme: 'Planet' },
  { theme: 'Plank', aliases: ['plank'] },
  { theme: 'Plant' },
  { theme: 'Plate', aliases: ['prato', 'plato', 'piatto', 'farfurie', '皿', '盘子', '盤子', '접시'] },
  { theme: 'Platform', aliases: ['alusta'] },
  { theme: 'Platypus' },
  { theme: 'Playground', aliases: ['hriste'] },
  { theme: 'Plug', aliases: ['kontakt'] },
  { theme: 'Plumber', aliases: ['vvs\'er'] },
  { theme: 'Plunger', aliases: ['pompel'] },
  { theme: 'Pocket Watch', aliases: ['fickur'] },
  { theme: 'Podium', aliases: ['podio', 'podium'] },
  { theme: 'Pogo Stick', aliases: ['pogo'] },
  { theme: 'Poison', aliases: ['gift'] },
  { theme: 'Polar Bear', aliases: ['eisbar'] },
  { theme: 'Police', aliases: ['poli', 'police', '警察'] },
  { theme: 'Police Car', aliases: ['radiowoz'] },
  { theme: 'Police Officer', aliases: ['poli', '警察'] },
  { theme: 'Police Station', aliases: ['karakol'] },
  { theme: 'Pond', aliases: ['to', 'lago'] },
  { theme: 'Pony' },
  { theme: 'Pool', aliases: ['basen', 'bazen', 'piscina', 'zwembad', 'piscine', 'medence', 'uima-alla', '游泳池', '수영장', 'басейн', 'бассейн', 'svømmebasseng'] },
  { theme: 'Pool table' },
  { theme: 'Popcorn', aliases: ['pipoca'] },
  { theme: 'Popsicle', aliases: ['nanuk'] },
  { theme: 'Portal' },
  { theme: 'Post Office', aliases: ['post', 'postá', 'posta', 'poczta', 'correio', 'почта'] },
  { theme: 'Postcard', aliases: ['postal'] },
  { theme: 'Poster', aliases: ['afis', 'cartel'] },
  { theme: 'Pot of Gold', aliases: ['potd\'or'] },
  { theme: 'Potato', aliases: ['potet'] },
  { theme: 'Potato Chips', aliases: ['chip', 'chips', 'batatafrita', 'patatasfritas', 'batatasfritas', '洋芋片'] },
  { theme: 'Potion', aliases: ['grog', 'drankje'] },
  { theme: 'Power Lines', aliases: ['电线', '電線', '전선'] },
  { theme: 'Present', aliases: ['gave', 'gift', 'cadou', 'hediye', 'regalo', 'cadeau', 'ajandek', 'present', 'presente', 'geschenk', '礼物', '禮物', '선물', 'подарок', 'подарунок'] },
  { theme: 'Presentation', aliases: ['sunum'] },
  { theme: 'Pretzel', aliases: ['perec'] },
  { theme: 'Prince', aliases: ['prin', 'prince'] },
  { theme: 'Princess', aliases: ['prince'] },
  { theme: 'Printer', aliases: ['yazici', 'skrivemaskin'] },
  { theme: 'Prison', aliases: ['prisao', 'prison', 'borton', 'vezeni', 'fengsel', 'vankila', 'fangelse', 'prigione', 'gefangnis', 'wiezienie', 'gevangeni', '监狱', '監獄', '감옥', 'тюрьма', 'fængsel', 'в\'язниця'] },
  { theme: 'Prison Cell', aliases: ['cela', 'cella'] },
  { theme: 'Prisoner', aliases: ['fange'] },
  { theme: 'Projectile', aliases: ['mermi'] },
  { theme: 'Propeller', aliases: ['propel'] },
  { theme: 'Pudding', aliases: ['pudin'] },
  { theme: 'Puddle', aliases: ['pla', 'balta'] },
  { theme: 'Puffin', aliases: ['marti'] },
  { theme: 'Pumpkin', aliases: ['tok'] },
  { theme: 'Puppet', aliases: ['bab', 'pop', 'dukke'] },
  { theme: 'Puppy', aliases: ['valp', 'cachorro'] },
  { theme: 'Purse', aliases: ['pung', 'borsa', 'canta', 'veske', 'geanta', 'torebka', 'carteira', 'penztarca', 'penezenka', 'portemonnee', 'porte-monnaie', '財布', '钱包', '지갑', '手提包', 'кошелёк', 'гаманець'] },
  { theme: 'Puzzle', aliases: ['yapboz', 'pussel', 'puzzle', 'puzzel', 'palapeli', 'ukladanka', 'puslespil', 'puslespill', '拼圖', 'пазл', 'quebra-cabeça'] },
  { theme: 'Puzzle Cube', aliases: ['hlavolam', 'rubikskub', 'rubikscube', 'rubikskube', 'rubikskubus', 'cubodirubik', 'cubo magico', 'cuboderubik', 'kostkarubika', '魔術方塊', 'кубикрубика', 'кубикрубіка'] },
  { theme: 'Pyjamas', aliases: ['pijama'] },
  { theme: 'Pyramid', aliases: ['pirami'] },
  { theme: 'QR Code' },
  { theme: 'Quad Bike', aliases: ['quad'] },
  { theme: 'Queen' },
  { theme: 'Quicksand', aliases: ['bataklik'] },
  { theme: 'Quiver', aliases: ['tobla'] },
  { theme: 'Rabbit', aliases: ['kani'] },
  { theme: 'Raccoon', aliases: ['raton'] },
  { theme: 'Race', aliases: ['gara', 'course', 'rennen', 'corrida'] },
  { theme: 'Race Track', aliases: ['circuito', 'tor wyscigowy'] },
  { theme: 'Racecar' },
  { theme: 'Radio' },
  { theme: 'Raft', aliases: ['sal', 'raft'] },
  { theme: 'Railway', aliases: ['vasut', 'rautatie'] },
  { theme: 'Rain', aliases: ['eso', 'regen', 'дождь'] },
  { theme: 'Rain Coat', aliases: ['regenja'] },
  { theme: 'Rainbow', aliases: ['tecza'] },
  { theme: 'Raindrop', aliases: ['regen', 'дождь'] },
  { theme: 'Rake', aliases: ['tirmik', '갈퀴'] },
  { theme: 'Ramen' },
  { theme: 'Rat', aliases: ['topo', 'rat', 'rata', 'rato', '老鼠'] },
  { theme: 'Ravine', aliases: ['vadi'] },
  { theme: 'Reading', aliases: ['ler'] },
  { theme: 'Reaper', aliases: ['kaszas', 'ceifador', 'mietitore', 'liemannen', 'viikatemie', 'sensenmann', 'mandenmedleen', '死神', 'døden', 'жнець'] },
  { theme: 'Recycle' },
  { theme: 'Red Panda' },
  { theme: 'Redstone', aliases: ['rudit'] },
  { theme: 'Reef', aliases: ['sandalia'] },
  { theme: 'Refrigerator', aliases: ['fridge', 'nevera', 'lodowka', 'kylskap', 'lednice', 'koelkast', 'frigider', 'jaakaappi', 'buzdolabi', 'frigorifero', 'frigorifico', 'kuhlschrank', 'hutoszekreny', 'refrigerateur', '冰箱', '冷蔵庫', '냉장고', 'køleskab', 'kjøleskap', 'холодильник'] },
  { theme: 'Remote', aliases: ['ovladac'] },
  { theme: 'Restaurant', aliases: ['etterem'] },
  { theme: 'Rhino' },
  { theme: 'Ribbon', aliases: ['band', 'cinta', 'szalag', 'стрічка'] },
  { theme: 'Rice', aliases: ['ri', 'rei'] },
  { theme: 'Rich', aliases: ['rig'] },
  { theme: 'Ride', aliases: ['ri', 'rit', 'passeio'] },
  { theme: 'Ring' },
  { theme: 'River', aliases: ['elv'] },
  { theme: 'Road', aliases: ['ut', 'дорога', 'tie', 'vag', 'drum', 'cesta', 'strada', 'straße'] },
  { theme: 'Robot', aliases: ['robo', 'robot'] },
  { theme: 'Rock', aliases: ['ko', 'rock', 'kivi', 'kős'] },
  { theme: 'Rock Band' },
  { theme: 'Rock Climbing', aliases: ['escalar', 'escalada', 'escalade', 'wspinaczka', 'arrampicata', 'horolezectvi', 'скелелазіння'] },
  { theme: 'Rocket', aliases: ['roket', 'raket', 'ракета', 'fusee', 'razzo', 'rakett', 'raketa', 'rakete', 'raketti', 'rakieta'] },
  { theme: 'Rocket Ship', aliases: ['roket', 'raket', 'ракета', 'fusee', 'razzo', 'rakett', 'raketti', 'rumskib', 'naveespacial', 'statekkosmiczny'] },
  { theme: 'Rocking Chair', aliases: ['gungstol'] },
  { theme: 'Roller Blades', aliases: ['paten', 'patine'] },
  { theme: 'Rollercoaster', aliases: ['achtbaan'] },
  { theme: 'Roof', aliases: ['tak', 'tag'] },
  { theme: 'Room', aliases: ['rom', 'sala', 'camera'] },
  { theme: 'Rose', aliases: ['ro'] },
  { theme: 'Roundabout', aliases: ['rondo'] },
  { theme: 'Rowboat', aliases: ['kajak', '划艇', 'лодка', 'човен'] },
  { theme: 'Rubber Band', aliases: ['lastik', 'гумка'] },
  { theme: 'Rubber Duck', aliases: ['seafilth'] },
  { theme: 'Rubbish', aliases: ['cop', 'poubelle', 'lixo', 'basura', 'skrap', 'gunoi', 'szemet', 'smieci', '垃圾', '쓰레기', 'мусор', 'søppel', 'сміття'] },
  { theme: 'Rubiks Cube', aliases: ['cubrubik', 'rubikskub', 'rubikscube', 'rubikskube', 'rubikskubus', 'cubodirubik', 'cubo magico', 'cuboderubik', 'kostkarubika', '魔術方塊', 'кубикрубика', 'кубикрубіка'] },
  { theme: 'Rug', aliases: ['teppe', 'tæppe', 'tapi', 'covor', 'matta', 'dywan', 'tapete', 'tapijt', 'tappeto', 'teppich', 'koberec', 'szonyeg', 'alfombra', '地毯', '양탄자', 'килим', 'ковёр'] },
  { theme: 'Ruins' },
  { theme: 'Ruler' },
  { theme: 'Runner', aliases: ['futo', 'correr', 'corredor'] },
  { theme: 'Running', aliases: ['futas', 'correr', 'course', 'rennen', 'behani', 'springa', 'бег', 'біг'] },
  { theme: 'Sad', aliases: ['sad'] },
  { theme: 'Saddle', aliases: ['sa', 'sal', 'så'] },
  { theme: 'Safari' },
  { theme: 'Safe', aliases: ['tresor', 'kasa', 'klui'] },
  { theme: 'Sailboat', aliases: ['velero'] },
  { theme: 'Salad', aliases: ['salat', 'sallad', 'salata', 'salade', 'салат'] },
  { theme: 'Salamander', aliases: ['mlok'] },
  { theme: 'Salmon', aliases: ['lak', 'lach'] },
  { theme: 'Saloon', aliases: ['bar', 'krog', '酒場', '酒店', '酒馆', '술집', 'бар'] },
  { theme: 'Salt', aliases: ['so', 'sal', 'sel', 'sol', 'tuz'] },
  { theme: 'Salt and Pepper', aliases: ['saleepepe'] },
  { theme: 'Samurai' },
  { theme: 'Sandbox' },
  { theme: 'Sandcastle', aliases: ['sandslot'] },
  { theme: 'Sandwich', aliases: ['sandvic'] },
  { theme: 'Santa' },
  { theme: 'Sardines' },
  { theme: 'Satellite', aliases: ['uydu'] },
  { theme: 'Sauce', aliases: ['so', 'sas', 'sau', 'salsa', 'så'] },
  { theme: 'Sausage', aliases: ['sosi'] },
  { theme: 'Savanna', aliases: ['savan'] },
  { theme: 'Saw', aliases: ['sega', 'serra', 'testere'] },
  { theme: 'Saxophone', aliases: ['saxofon'] },
  { theme: 'Scaffold', aliases: ['schela'] },
  { theme: 'Scale', aliases: ['vaha', 'scala'] },
  { theme: 'Scarecrow', aliases: ['strasak'] },
  { theme: 'Scared', aliases: ['redd'] },
  { theme: 'Scarf', aliases: ['sal'] },
  { theme: 'School Bus', aliases: ['skolbus'] },
  { theme: 'Science', aliases: ['veda'] },
  { theme: 'Scientist', aliases: ['tudos'] },
  { theme: 'Scooby Doo' },
  { theme: 'Scooter', aliases: ['skutr'] },
  { theme: 'Scorpion', aliases: ['akrep'] },
  { theme: 'Screen', aliases: ['tela', 'ecran', 'skjerm', 'pantalla', 'bildschirm', 'skærm'] },
  { theme: 'Screwdriver', aliases: ['tournevi'] },
  { theme: 'Scuba Diving', aliases: ['scuba'] },
  { theme: 'Scythe', aliases: ['le', 'falce', 'foice', 'secera', 'коса'] },
  { theme: 'Sea Turtle', aliases: ['черепаха', '海龟'] },
  { theme: 'Seafood' },
  { theme: 'Seagull', aliases: ['make', 'marti'] },
  { theme: 'Seahorse', aliases: ['sjohast', '해마'] },
  { theme: 'Seal', aliases: ['sel', 'sal', 'sello'] },
  { theme: 'Seat', aliases: ['loc', 'stoel', 'koltuk', 'シート'] },
  { theme: 'Seaweed', aliases: ['alga', 'tang', 'algue', 'hinar', 'seetang', 'zeewier', 'merileva', 'водоросли'] },
  { theme: 'Security Camera' },
  { theme: 'Seed', aliases: ['mag'] },
  { theme: 'Seesaw', aliases: ['vippe', 'altalena', 'hustawka', 'houpacka', 'balancoire', 'качели', 'гойдалка'] },
  { theme: 'Self Portrait', aliases: ['portre'] },
  { theme: 'Sewer', aliases: ['csatorna'] },
  { theme: 'Sewing Machine', aliases: ['varrogep'] },
  { theme: 'Shack', aliases: ['skur', 'schuur', '小屋', 'хижина', 'buda', 'hutte', 'kulube', 'cabana', 'kunyho', 'capanna', '오두막', 'хатина'] },
  { theme: 'Shadow', aliases: ['cien'] },
  { theme: 'Shampoo', aliases: ['shampo'] },
  { theme: 'Shapes' },
  { theme: 'Shark', aliases: ['haj', 'capa'] },
  { theme: 'Shaving', aliases: ['tiras'] },
  { theme: 'Shed', aliases: ['schuur', '小屋', 'skur', 'bouda', '헛간', 'сарай'] },
  { theme: 'Sheep', aliases: ['far', 'sau', 'barany'] },
  { theme: 'Sheet', aliases: ['ark', 'hoja', 'folha', 'drap', 'blatt', 'シート', 'лист'] },
  { theme: 'Shelf', aliases: ['raf', 'raft', 'plank', 'police'] },
  { theme: 'Shell', aliases: ['skal', 'kagylo', 'muschel', 'simpukka'] },
  { theme: 'Shelter', aliases: ['ly', 'abrigo', 'siginak'] },
  { theme: 'Shield', aliases: ['pajz', 'schild'] },
  { theme: 'Ship', aliases: ['lod', 'barco', 'bateau', '船'] },
  { theme: 'Shipwreck', aliases: ['wrak'] },
  { theme: 'Shirt', aliases: ['ing', 'troja', 'tricou'] },
  { theme: 'Shoe Laces', aliases: ['lacet'] },
  { theme: 'Shoes', aliases: ['sko', 'boty', 'buty', 'schuhe', '신발'] },
  { theme: 'Shop', aliases: ['magazin', 'loja', 'bolt', 'sklep', 'butik', 'kauppa', 'tienda', 'obchod', 'winkel', 'butikk', 'magaza', 'negozio', 'boutique', '商店', '상점', 'магазин', 'крамниця'] },
  { theme: 'Shopping Bag', aliases: ['handlepose', '장바구니'] },
  { theme: 'Shopping Trolley', aliases: ['caddie', 'einkaufswagen', 'bevasarlokocsi', 'carrinhodecompras', 'indkøbsvogn'] },
  { theme: 'Short', aliases: ['sort', 'kort', 'short', 'bermuda', 'pantalone', 'kortebroek', 'rovidnadrag', '반바지', 'шорты'] },
  { theme: 'Shorts', aliases: ['sort', 'short', 'bermuda', 'kortebroek', 'rovidnadrag', '반바지', 'шорты'] },
  { theme: 'Shoulder', aliases: ['vall'] },
  { theme: 'Shovel', aliases: ['pa', 'palas', 'pala', 'pelle', 'aso', 'spade', 'kurek', 'lapio', 'schep', '锹', '鏟子', 'лопата'] },
  { theme: 'Shower', aliases: ['dus'] },
  { theme: 'Shuriken' },
  { theme: 'Sickle', aliases: ['hoz', 'falce', 'foice', 'secera', 'коса'] },
  { theme: 'Sidewalk', aliases: ['jarda', 'fortau', 'calcada', 'passeio'] },
  { theme: 'Sign', aliases: ['bord', 'schild', 'cartel'] },
  { theme: 'Signal', aliases: ['jel'] },
  { theme: 'Silo', aliases: ['бункер'] },
  { theme: 'Silver', aliases: ['plata'] },
  { theme: 'Sing', aliases: ['canta'] },
  { theme: 'Sink', aliases: ['pia'] },
  { theme: 'Skateboarding', aliases: ['skate'] },
  { theme: 'Skating', aliases: ['schaatsen'] },
  { theme: 'Skeleton', aliases: ['skelet'] },
  { theme: 'Ski', aliases: ['si', 'kayak', 'sci', 'ski', 'esqui', 'esquiar', 'skidakning', '滑雪', '스키', 'スキー', 'лижі'] },
  { theme: 'Skiing', aliases: ['ski', 'kayak', 'sci', 'esqui', 'esquiar', 'skidakning', '滑雪', '스키', 'スキー', 'лижі'] },
  { theme: 'Skirt', aliases: ['rok', 'rock'] },
  { theme: 'Skull', aliases: ['kopf', 'crane', 'cabeza'] },
  { theme: 'SkyBlock' },
  { theme: 'Skydiver' },
  { theme: 'Skyscraper', aliases: ['gokdelen'] },
  { theme: 'SkyWars' },
  { theme: 'Sleep', aliases: ['sen', 'sova'] },
  { theme: 'Sleeping Bag', aliases: ['spiwor'] },
  { theme: 'Sleigh', aliases: ['slee'] },
  { theme: 'Slide', aliases: ['tobogan'] },
  { theme: 'Slime', aliases: ['slim', 'слимак', 'слизень'] },
  { theme: 'Slippers', aliases: ['papuc', 'sandalia'] },
  { theme: 'Sloth' },
  { theme: 'Slug', aliases: ['melc', 'etana', 'snegle', 'slimak', 'snigel', 'lumaca', 'слимак', 'слизень'] },
  { theme: 'Smartphone', aliases: ['handy'] },
  { theme: 'Smell', aliases: ['geur'] },
  { theme: 'Smelting', aliases: ['fonte'] },
  { theme: 'Smile', aliases: ['lach', 'mosoly', 'sorriso', 'sonrisa', 'usmiech'] },
  { theme: 'Smiley', aliases: ['hymio', 'mosoly', 'sorriso', 'sonrisa', 'usmiech', 'смайлик'] },
  { theme: 'Smoke', aliases: ['si', 'rok'] },
  { theme: 'Smoothie', aliases: ['frappe'] },
  { theme: 'Smore', aliases: ['棉花糖'] },
  { theme: 'Snail', aliases: ['melc', 'etana', 'snegle', 'slimak', 'snigel', 'lumaca'] },
  { theme: 'Snake', aliases: ['orm'] },
  { theme: 'Sneakers', aliases: ['tenis'] },
  { theme: 'Snow', aliases: ['ho', '눈', 'hő', 'neve', 'snieg', 'снег'] },
  { theme: 'Snowball', aliases: ['snoboll'] },
  { theme: 'Snowboarding', aliases: ['snowboard'] },
  { theme: 'Snowflake', aliases: ['snefnug'] },
  { theme: 'Snowing', aliases: ['snieg', '눈', 'снег'] },
  { theme: 'Snowman', aliases: ['balwan', '雪人'] },
  { theme: 'Soap' },
  { theme: 'Soccer', aliases: ['foci', 'soccer', 'futbol', 'fotboll', 'football', 'jalkapallo', '足球', 'футбол'] },
  { theme: 'Socks', aliases: ['meia', 'media', 'chaussette'] },
  { theme: 'Soda', aliases: ['bru', 'limonade'] },
  { theme: 'Sofa', aliases: ['sofa', 'sohva', 'divano', 'koltuk', '沙发', '沙發', '소파', 'диван'] },
  { theme: 'Soil', aliases: ['sol', 'erde', 'terre', 'tierra'] },
  { theme: 'Solar System', aliases: ['solsystem'] },
  { theme: 'Sound', aliases: ['se', 'son'] },
  { theme: 'Soup', aliases: ['leve'] },
  { theme: 'Space', aliases: ['ur'] },
  { theme: 'Spaceship', aliases: ['urhajo', 'rumskib', 'naveespacial', 'statekkosmiczny', 'űrhajó'] },
  { theme: 'Spade', aliases: ['pa', 'palas', 'pala', 'pelle', 'aso', 'spade', 'kurek', 'lapio', 'schep', '锹', '鏟子', 'лопата'] },
  { theme: 'Spaghetti', aliases: ['spagety'] },
  { theme: 'Sparkler', aliases: ['maytap', 'bengala'] },
  { theme: 'Speakers', aliases: ['boxe', '喇叭'] },
  { theme: 'Spear', aliases: ['spyd'] },
  { theme: 'Speedboat', aliases: ['lancha', 'motoscafo'] },
  { theme: 'Sphere', aliases: ['bol', 'kure', 'gomb', 'sfera', '원형'] },
  { theme: 'Spider', aliases: ['pok'] },
  { theme: 'Spider Web', aliases: ['pokhalo', 'telarana', 'pavucina', 'ragnatela', 'spinnenweb', 'spindelvev', 'spindelnat', 'spinnennetz', 'teiadearanha', 'toile d\'araignee', '蜘蛛網', '거미줄', 'クモの巣', 'паутина', 'spindelvæv', 'pajeczyna', 'orumcek agi', '蜘蛛网', 'павутина'] },
  { theme: 'Spiral Staircase', aliases: ['wenteltrap'] },
  { theme: 'Spleef' },
  { theme: 'Sponge', aliases: ['spon', 'svamp'] },
  { theme: 'Spoon', aliases: ['ske', 'kanal'] },
  { theme: 'Sports' },
  { theme: 'Spray' },
  { theme: 'Spring', aliases: ['var'] },
  { theme: 'Sprinkler', aliases: ['fiskiye'] },
  { theme: 'Sprint', aliases: ['correr', 'springa', 'бег', 'біг'] },
  { theme: 'Spy' },
  { theme: 'Square', aliases: ['kare'] },
  { theme: 'Squid', aliases: ['lula', 'kraken', 'poulpe', 'inktvi', 'blackfisk', 'blekksprut', 'blæksprutte'] },
  { theme: 'Squirrel', aliases: ['orava'] },
  { theme: 'Stables', aliases: ['stald'] },
  { theme: 'Stadium', aliases: ['stade'] },
  { theme: 'Stage', aliases: ['lava', 'podium'] },
  { theme: 'Staircase', aliases: ['scala', 'escalera', 'merdiven', 'лестница'] },
  { theme: 'Stamp', aliases: ['pul', 'sello', 'stempel'] },
  { theme: 'Star' },
  { theme: 'Starfish', aliases: ['zeester'] },
  { theme: 'Statue', aliases: ['socha'] },
  { theme: 'Steak', aliases: ['file', 'biff', 'bife', 'biftek', 'bøf'] },
  { theme: 'Steering Wheel', aliases: ['rat'] },
  { theme: 'Step Ladder', aliases: ['stege', 'letra', 'escada', 'tikkaat', 'драбина'] },
  { theme: 'Step Stool', aliases: ['pall', 'escada'] },
  { theme: 'Stepping Stones', aliases: ['calcada'] },
  { theme: 'Stereo' },
  { theme: 'Sticky Note', aliases: ['note'] },
  { theme: 'Stingray', aliases: ['raja'] },
  { theme: 'Stocking', aliases: ['kou', 'meia', 'media', 'chaussette'] },
  { theme: 'Stop Sign' },
  { theme: 'Stopwatch', aliases: ['stoper'] },
  { theme: 'Storage', aliases: ['lager', 'magazyn', 'сховище'] },
  { theme: 'Store', aliases: ['loja', 'magazin', 'sklep', 'butik', 'kauppa', 'tienda', 'market', 'obchod', 'winkel', 'butikk', 'magaza', 'negozio', 'boutique', '商店', '상점', 'магазин', 'крамниця'] },
  { theme: 'Storm', aliases: ['firtina', 'vihar', 'orage', 'furtuna', 'tormenta'] },
  { theme: 'Stove', aliases: ['spi', 'печь', 'piec', 'estufa'] },
  { theme: 'Straw', aliases: ['pai'] },
  { theme: 'Strawberry', aliases: ['eper'] },
  { theme: 'Street', aliases: ['rua', 'gate', 'strada', 'straße'] },
  { theme: 'Streetlamp', aliases: ['farola', 'latarnia', 'lampione', 'lampadaire', 'postedeluz', 'фонарныйстолб'] },
  { theme: 'String', aliases: ['ip', 'fio', 'trad', 'lanka', 'linha', '線', '线'] },
  { theme: 'Strong', aliases: ['eros', 'sterk'] },
  { theme: 'Stronghold', aliases: ['erod', 'крепость', 'festung', 'masmorra', 'twierdza', 'linnoitu', 'fortaleza', 'forteresse', '要塞', 'фортеця'] },
  { theme: 'Submarine', aliases: ['ubad', 'submarino'] },
  { theme: 'Sugar', aliases: ['cukr', 'seker'] },
  { theme: 'Suit', aliases: ['pak', 'abito', 'stroj'] },
  { theme: 'Suitcase', aliases: ['mala', 'bavul'] },
  { theme: 'Summer', aliases: ['ete', 'vara'] },
  { theme: 'Sumo', aliases: ['sumo'] },
  { theme: 'Sun', aliases: ['sol', 'nap'] },
  { theme: 'Sunbed', aliases: ['lezak'] },
  { theme: 'Sunflower', aliases: ['solro'] },
  { theme: 'Sunglasses' },
  { theme: 'Sunken Airplane', aliases: ['sunketfly'] },
  { theme: 'Sunlight', aliases: ['solly', 'swiatlo'] },
  { theme: 'Sunrise', aliases: ['alba'] },
  { theme: 'Sunset' },
  { theme: 'Superhero' },
  { theme: 'Supermarket', aliases: ['supermarkt'] },
  { theme: 'Surfboard' },
  { theme: 'Surfing', aliases: ['surf'] },
  { theme: 'Survival Games' },
  { theme: 'Sushi', aliases: ['susi'] },
  { theme: 'Swamp', aliases: ['suo', 'bagno', 'bataklik'] },
  { theme: 'Swan', aliases: ['svan', 'labut'] },
  { theme: 'Sweater', aliases: ['pull', 'troja'] },
  { theme: 'Swimming', aliases: ['inot'] },
  { theme: 'Swimming Pool', aliases: ['basen', 'bazen', 'piscina', 'zwembad', 'piscine', 'medence', 'uima-alla', '游泳池', '수영장', 'басейн', 'бассейн', 'svømmebasseng'] },
  { theme: 'Swing', aliases: ['altalena', 'hustawka', 'houpacka', 'columpio', 'balancoire', 'качели', 'гойдалка'] },
  { theme: 'Swiss Cheese', aliases: ['quesosuizo'] },
  { theme: 'Switch', aliases: ['spak', 'kontakt', 'interruptor', 'interrupteur'] },
  { theme: 'Sword', aliases: ['mec', 'kilic'] },
  { theme: 'Swordfish', aliases: ['mecoun'] },
  { theme: 'T-Rex', aliases: ['trex'] },
  { theme: 'T-Shirt', aliases: ['polo', 'tricou'] },
  { theme: 'Table', aliases: ['masa', 'bord', 'mesa', 'stol', 'tafel', 'tavolo', '桌子', 'стол', 'стіл'] },
  { theme: 'Table Cloth', aliases: ['dug', 'mantel'] },
  { theme: 'Table Tennis', aliases: ['bordtenni'] },
  { theme: 'Tablet' },
  { theme: 'Taco' },
  { theme: 'Tail', aliases: ['oca', 'hale', 'cola', 'svan'] },
  { theme: 'Tall', aliases: ['tall', 'høy'] },
  { theme: 'Tape', aliases: ['band', 'banda', 'cinta', 'szalag', 'стрічка'] },
  { theme: 'Target', aliases: ['cel', 'mal', 'tinta'] },
  { theme: 'Tattoo', aliases: ['dovme'] },
  { theme: 'Tavern', aliases: ['kro', '酒馆'] },
  { theme: 'Taxi', aliases: ['taxi', 'taksi', 'taksowka', '택시', '出租车', '計程車', 'タクシー', 'такси', 'таксі'] },
  { theme: 'Tea', aliases: ['te'] },
  { theme: 'Teapot', aliases: ['tetera', 'чайник'] },
  { theme: 'Tears', aliases: ['lzy'] },
  { theme: 'Technology', aliases: ['teknik'] },
  { theme: 'Teddy Bear', aliases: ['bamse'] },
  { theme: 'Teeth', aliases: ['dent', 'dente', 'diente', '歯', '牙齒', '牙齿', '치아'] },
  { theme: 'Telephone', aliases: ['telefon'] },
  { theme: 'Telephone Booth', aliases: ['telefonboks'] },
  { theme: 'Telescope', aliases: ['teleskop'] },
  { theme: 'Television', aliases: ['tv'] },
  { theme: 'Temple', aliases: ['chram', 'templom'] },
  { theme: 'Tennis', aliases: ['teni', 'tenis', '網球', '网球'] },
  { theme: 'Tennis Ball', aliases: ['tenisak', '網球', '网球'] },
  { theme: 'Tennis Court', aliases: ['teniskortu'] },
  { theme: 'Tent', aliases: ['tenda'] },
  { theme: 'Tetris' },
  { theme: 'Texting', aliases: ['sms'] },
  { theme: 'Thanksgiving', aliases: ['halaadas'] },
  { theme: 'The End', aliases: ['son'] },
  { theme: 'Theater', aliases: ['teatr', 'theater'] },
  { theme: 'Theme Park', aliases: ['pretpark', 'vidampark'] },
  { theme: 'Thermometer', aliases: ['homero'] },
  { theme: 'Thief', aliases: ['tyv', 'vara'] },
  { theme: 'Throne', aliases: ['taht'] },
  { theme: 'Thug', aliases: ['criminal', 'злочинець'] },
  { theme: 'Thumb', aliases: ['duim', 'palec'] },
  { theme: 'Thunder', aliases: ['aska', 'firtina', 'donder', 'relampago', 'гроза'] },
  { theme: 'Thunderstorm', aliases: ['vihar', 'firtina', 'orage', 'donder', 'furtuna', 'гроза'] },
  { theme: 'Tic Tac Toe', aliases: ['tri'] },
  { theme: 'Ticket', aliases: ['jegy'] },
  { theme: 'Tie', aliases: ['tie', '领带'] },
  { theme: 'Tiger', aliases: ['tygr'] },
  { theme: 'Time Machine', aliases: ['idogep'] },
  { theme: 'Tin Can', aliases: ['lata', 'puszka', 'lattina', 'plechovka', 'hermetikkbok', 'konzervdoboz', '罐头'] },
  { theme: 'Tinsel', aliases: ['suslu'] },
  { theme: 'Tire Swing', aliases: ['anvelopa', 'columpio'] },
  { theme: 'Tissue', aliases: ['serviett', 'servetel'] },
  { theme: 'Titanic', aliases: ['거대한'] },
  { theme: 'TNT', aliases: ['tnt', 'dynamit', 'dinamite', 'dynamite', 'динамит', 'динаміт'] },
  { theme: 'TNT Cannon', aliases: ['tuntnt'] },
  { theme: 'Toad', aliases: ['pad', 'жаба', 'sapo', 'kurbaga'] },
  { theme: 'Toast', aliases: ['tost'] },
  { theme: 'Toaster', aliases: ['toster'] },
  { theme: 'Toes' },
  { theme: 'Toilet', aliases: ['vessa', 'toilet'] },
  { theme: 'Toilet Paper', aliases: ['wc papir'] },
  { theme: 'Tomato', aliases: ['tomat'] },
  { theme: 'Tomato Ketchup', aliases: ['ketcap', 'keczup', 'ketchup', '番茄酱', '番茄醬', 'кетчуп'] },
  { theme: 'Tongue', aliases: ['dil'] },
  { theme: 'Tools' },
  { theme: 'Tooth', aliases: ['fog', 'dent', 'dente', 'diente', '歯', '牙齒', '牙齿', '치아'] },
  { theme: 'Tooth Fairy', aliases: ['tandfe'] },
  { theme: 'Toothbrush', aliases: ['fogkefe'] },
  { theme: 'Toothpaste', aliases: ['fogkrem'] },
  { theme: 'Top Hat', aliases: ['joben'] },
  { theme: 'Torch', aliases: ['louc', 'torta', 'torcia'] },
  { theme: 'Tornado', aliases: ['hortum'] },
  { theme: 'Tortoise', aliases: ['zolw', 'черепаха', 'tortue', 'teknos', 'tartaruga', 'skoldpadda', 'kilpikonna', '烏龜'] },
  { theme: 'Totem Pole', aliases: ['totem'] },
  { theme: 'Towel', aliases: ['serviette'] },
  { theme: 'Towel Rack', aliases: ['havluluk'] },
  { theme: 'Tower of Pisa' },
  { theme: 'Toy', aliases: ['jatek'] },
  { theme: 'Toy Soldier', aliases: ['vojacek'] },
  { theme: 'Track', aliases: ['iz', 'дорога', 'rata', 'circuito', 'tor wyscigowy'] },
  { theme: 'Tractor', aliases: ['trator'] },
  { theme: 'Traffic', aliases: ['trafik', '교통'] },
  { theme: 'Traffic Jam', aliases: ['file', 'trafik'] },
  { theme: 'Traffic Lights', aliases: ['ampel'] },
  { theme: 'Trailer', aliases: ['prives'] },
  { theme: 'Train Station', aliases: ['gara'] },
  { theme: 'Train Tracks', aliases: ['rail', 'rautatie'] },
  { theme: 'Trains', aliases: ['tag'] },
  { theme: 'Trampoline', aliases: ['trampolin'] },
  { theme: 'Transport', aliases: ['ulasim', 'транспорт', 'kuljetu', 'transport', 'transporte', '运输'] },
  { theme: 'Transportation', aliases: ['ulasim', 'транспорт', 'kuljetu', 'vervoer', 'transport', 'transporte', '运输', '교통'] },
  { theme: 'Trap', aliases: ['val'] },
  { theme: 'Trash Can', aliases: ['kosz', 'poubelle', 'mulleimer', 'cop kutusu', 'skraldespand', 'ゴミ箱', '垃圾桶', '쓰레기통', 'мусорноеведро', 'lixeira', 'cestino', 'roskakori', 'vuilnisbak', 'cos de gunoi', 'odpadkovy kos', 'caixotedolixo', 'смітник', 'søppelkasse'] },
  { theme: 'Treadmill', aliases: ['futopad', 'tapisroulant'] },
  { theme: 'Treasure', aliases: ['skat', 'tresor'] },
  { theme: 'Treasure Chest', aliases: ['schatkist'] },
  { theme: 'Tree', aliases: ['fa', 'fas', 'trad', 'træ'] },
  { theme: 'Tree Frog', aliases: ['ra', 'жаба'] },
  { theme: 'Treehouse', aliases: ['fahaz', 'trehytte'] },
  { theme: 'Triangle', aliases: ['ucgen'] },
  { theme: 'Trick Shot' },
  { theme: 'Tricycle', aliases: ['dreirad'] },
  { theme: 'Trolley', aliases: ['vogn', 'vagn', 'vozik', 'carrello', 'einkaufswagen', 'bevasarlokocsi', 'carrinhodecompras', 'indkøbsvogn'] },
  { theme: 'Trophy', aliases: ['kupa', 'palkinto'] },
  { theme: 'Trousers', aliases: ['hose', 'pantalone'] },
  { theme: 'Truck', aliases: ['lkw'] },
  { theme: 'Trumpet', aliases: ['tromba'] },
  { theme: 'Tsunami', aliases: ['cunami'] },
  { theme: 'Tub', aliases: ['banheira', 'wanna', 'banera', 'baignoire', '浴缸', '욕조', 'ванна'] },
  { theme: 'Tuba' },
  { theme: 'Tug of War', aliases: ['drakamp'] },
  { theme: 'Tuna', aliases: ['tun', 'ton'] },
  { theme: 'Tunnel', aliases: ['tunel'] },
  { theme: 'Turkey', aliases: ['peru'] },
  { theme: 'Turret', aliases: ['torn', 'robot'] },
  { theme: 'Turtle', aliases: ['zolw', 'черепаха', 'tortue', 'teknos', 'tartaruga', 'skoldpadda', 'kilpikonna', '海龟', '烏龜'] },
  { theme: 'Twig', aliases: ['tak'] },
  { theme: 'Typewriter', aliases: ['irogep', 'skrivemaskin'] },
  { theme: 'Tyre', aliases: ['band', 'lastik', 'anvelopa'] },
  { theme: 'UFO' },
  { theme: 'Ukulele', aliases: ['uke'] },
  { theme: 'Umbrella', aliases: ['umbrela'] },
  { theme: 'Undead', aliases: ['ododa'] },
  { theme: 'Under The Sea', aliases: ['submare', 'pod woda', 'vizalatti vilag'] },
  { theme: 'Underwater', aliases: ['sualti', 'pod woda', 'submarino', 'vizalatti vilag'] },
  { theme: 'Unicorn' },
  { theme: 'Unicycle', aliases: ['einrad', 'monocykl', 'моноцикл'] },
  { theme: 'University', aliases: ['egyetem'] },
  { theme: 'Upside Down', aliases: ['ter'] },
  { theme: 'Vacuum', aliases: ['vacuo'] },
  { theme: 'Valentine', aliases: ['sevgili'] },
  { theme: 'Vampire', aliases: ['upir'] },
  { theme: 'Van' },
  { theme: 'Vase', aliases: ['va'] },
  { theme: 'Vault', aliases: ['kasa', 'tresor', 'klui', 'сховище'] },
  { theme: 'Vegetable Garden', aliases: ['orto'] },
  { theme: 'Vegetables', aliases: ['sebze'] },
  { theme: 'Vehicle', aliases: ['tasit', 'транспорт'] },
  { theme: 'Vending Machine', aliases: ['otomat', 'automat'] },
  { theme: 'Video games', aliases: ['jogo'] },
  { theme: 'Viking' },
  { theme: 'Village', aliases: ['by', 'vila'] },
  { theme: 'Villager', aliases: ['bybo'] },
  { theme: 'Violin', aliases: ['fiol'] },
  { theme: 'Virtual Reality', aliases: ['vr'] },
  { theme: 'Volcano', aliases: ['vulkan'] },
  { theme: 'Volleyball', aliases: ['volei'] },
  { theme: 'Vulture', aliases: ['gam', 'vultur', '독수리'] },
  { theme: 'Waffle', aliases: ['vafa'] },
  { theme: 'Wagon', aliases: ['vagn', 'vogn', 'carro', 'vagon', 'waggon', 'carroca', 'carrinhodemina', '馬車', '马车', '마차'] },
  { theme: 'Wall', aliases: ['fal', 'wand'] },
  { theme: 'Wallet', aliases: ['pung', 'carteira', 'penztarca', 'penezenka', 'portemonnee', 'porte-monnaie', '財布', '钱包', '지갑', 'кошелёк', 'гаманець'] },
  { theme: 'Wallpaper', aliases: ['tapet'] },
  { theme: 'Walrus', aliases: ['mor', '해마'] },
  { theme: 'Wand', aliases: ['asa', 'wand', 'taikasauva', 'zauberstab', 'tryllestav', 'bagheta magica', 'varinha magica', 'baguettemagique', 'bacchettamagica', '杖', '지팡이', 'волшебнаяпалочка'] },
  { theme: 'Wardrobe', aliases: ['szafa', 'armario', 'armadio', 'garderob', '옷장'] },
  { theme: 'Warrior', aliases: ['harco'] },
  { theme: 'Washing Machine', aliases: ['pralka'] },
  { theme: 'Wasp', aliases: ['osa'] },
  { theme: 'Watch', aliases: ['ur', 'klokke', 'horloge', 'relogio', 'orologio', '시계', 'часы', 'годинник'] },
  { theme: 'Water', aliases: ['su', 'apa', 'sus'] },
  { theme: 'Water Balloon', aliases: ['subalonu'] },
  { theme: 'Water Bottle', aliases: ['waterfle'] },
  { theme: 'Water Bucket', aliases: ['sukovasi'] },
  { theme: 'Water Park', aliases: ['suparki'] },
  { theme: 'Water Slide', aliases: ['tobogan'] },
  { theme: 'Waterfall', aliases: ['fos'] },
  { theme: 'Watermelon', aliases: ['arbuz'] },
  { theme: 'Waterski', aliases: ['vizisi'] },
  { theme: 'Wave', aliases: ['vag', 'val', 'vlna'] },
  { theme: 'Weather', aliases: ['saa', 'vader'] },
  { theme: 'Web', aliases: ['ag', 'pokhalo', 'telarana', 'pavucina', 'ragnatela', 'spinnenweb', 'spindelvev', 'spindelnat', 'spinnennetz', 'teiadearanha', 'toile d\'araignee', '蜘蛛網', '거미줄', 'クモの巣', 'паутина', 'spindelvæv', 'panza', 'павутина'] },
  { theme: 'Wedding', aliases: ['haat'] },
  { theme: 'Wedding Cake', aliases: ['haakakku'] },
  { theme: 'Weightlifting', aliases: ['vzpirani'] },
  { theme: 'Well', aliases: ['tja', 'kaivo', 'fantana'] },
  { theme: 'Werewolf', aliases: ['varulv'] },
  { theme: 'Western', aliases: ['wester', 'ковбой'] },
  { theme: 'Whale', aliases: ['val'] },
  { theme: 'Wheat', aliases: ['ble'] },
  { theme: 'Wheel', aliases: ['rad', 'kolo'] },
  { theme: 'Wheelie', aliases: ['keulia', 'monocykl', 'моноцикл'] },
  { theme: 'Whirlpool', aliases: ['wir', 'whirlpool'] },
  { theme: 'Whistle', aliases: ['sip', 'fløjte', 'fløyte'] },
  { theme: 'Whiteboard', aliases: ['tavle'] },
  { theme: 'Wig' },
  { theme: 'Wind' },
  { theme: 'Windmill', aliases: ['moinho'] },
  { theme: 'Window', aliases: ['okno'] },
  { theme: 'Wings', aliases: ['asa', 'aile', 'vinger'] },
  { theme: 'Wink' },
  { theme: 'Winter', aliases: ['kis'] },
  { theme: 'Wire', aliases: ['fio', 'cavo', 'lanka', 'cable', 'kabel', 'kablo', 'cablu', '电线', '電線', '전선'] },
  { theme: 'Wishing well', aliases: ['wensput'] },
  { theme: 'Witch', aliases: ['hek'] },
  { theme: 'Witch Hut' },
  { theme: 'Wither' },
  { theme: 'Wizard', aliases: ['velho', 'magicien', 'sihirbaz', 'волшебник'] },
  { theme: 'Wolf', aliases: ['vlk', 'susi'] },
  { theme: 'Wool', aliases: ['la', 'vlna', 'villa', 'lå'] },
  { theme: 'Workshop', aliases: ['dilna', 'oficina'] },
  { theme: 'Worm', aliases: ['orm', 'mask', 'robak'] },
  { theme: 'Wrecking Ball', aliases: ['yikimtopu'] },
  { theme: 'Wrench' },
  { theme: 'Wrestling', aliases: ['gures'] },
  { theme: 'Xylophone', aliases: ['xylofon'] },
  { theme: 'Yacht', aliases: ['yat'] },
  { theme: 'Yeti', aliases: ['雪人', 'йети'] },
  { theme: 'Yogurt', aliases: ['yogur'] },
  { theme: 'Youtube' },
  { theme: 'Zebra' },
  { theme: 'Zeus' },
  { theme: 'Zip Line', aliases: ['молния-застёжка', 'застібкаблискавка'] },
  { theme: 'Zipper', aliases: ['rit', 'молния-застёжка', 'застібкаблискавка'] },
  { theme: 'Zombie Apocalypse', aliases: ['zombikiyameti'] },
  { theme: 'Zoo' },
];